### ISSUE TITLE
Import secrets from file using API

### ISSUE THREAD

**Issue by alexellis** [bitnami-labs/sealed-secrets#103]
Hi I would like to import a SealedSecret from a file. I can do this right now with `kubectl apply -f`, but I need to import it via the API since the `kubectl` binary wouldn't be available in my execution context.

In the integration tests I saw plaintext being encrypted as a new SealedSecret using a PublicKey - https://github.com/bitnami-labs/sealed-secrets/blob/master/integration/controller_test.go#L85

I would like to import a SealedSecret which was created ahead of time and dumped in a git repo. Does that API exist currently?

Thanks,

Alex

**Comment by anguslees** [comment]
I'm a little unclear what you mean by "import via the API", so please re-ask if this isn't what you were asking:

The sealing certificate can be fetched with `kubeseal --fetch-cert > /some/file.crt` (this step requires access to the k8s cluster), and is not secret (so can be stored/shared publicly if you want).
Once you have the certificate, you can encrypt a plain text Secret to an encrypted SealedSecret with `kubeseal --cert $cert < /some/secret/file.yaml` (this step does _not_ require access to the k8s cluster).  

So this allows you to create a SealedSecret ahead of time, and without access to the final cluster.  The SealedSecret object can be stored in git, just like all your other k8s config.

At _some_ point you want to push the git config (including SealedSecret) to the k8s cluster.  You should be able to push the SealedSecret object using whatever tooling you're using for all your other k8s config objects.  `kubectl apply -f ...`, `kubecfg update ...`, [weave cloud deploy](https://github.com/sebgoa/gitops-with-sealed-secrets), openshift config pipeline, etc, etc.

**Comment by alexellis** [comment]
Hi Angus, it sounds like you're following what I wanted to get to. I want an example in the docs of how to import that SealedSecret via Go instead of kubectl apply. I think I've figured it out now after digging through the code and the integration test, but it'd be good if you could confirm this.

Also wanted to know if there secret name affects any salting or hashing of the value in the encrypted data? I.e. could I create a secret, seal it then import it with a different name?

Thanks for your assistance.

**Comment by anguslees** [comment]
Manipulating the SealedSecret resource via the k8s API is [super-normal CRD stuff](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), so I strongly doubt my writing abilities will do any better than what the broader k8s community has already explained on this topic - and certainly not across the same breadth of client environments and levels of detail ;)  I'm happy to help where I can, but I encourage you to look there and at other examples of code using `client-gen`-based clients as a starting point.

> Also wanted to know if there secret name affects any salting or hashing of the value in the encrypted data?

Yes, the controller will only decrypt the SealedSecret if the namespace+name matches the one it was originally encrypted with ([docs](https://github.com/bitnami-labs/sealed-secrets#details)).

As you might have seen in the test suite, you _can_ disable this with a `sealedsecrets.bitnami.com/cluster-wide: true` [annotation](https://godoc.org/github.com/bitnami-labs/sealed-secrets/pkg/apis/sealed-secrets/v1alpha1#pkg-constants) on the original Secret (which then triggers `kubeseal` to encrypt it differently) - with the caveat that this allows anyone with the RBAC permissions to create a SealedSecret anywhere in your cluster to decrypt such a SealedSecret (since they can now copy your SealedSecret to their own namespace/name).  This feature is supported by the controller, but new enough that it isn't documented beyond [the release notes](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.6.0), nor exposed in `kubeseal` in a discoverable way yet (patches welcome!)
