### ISSUE TITLE
ETA on 0.8.0 Release?

### ISSUE THREAD

**Issue by mweinand** [bitnami-labs/sealed-secrets#106]
Really need the fix in #87, hoping an official release comes down soon.  Building from source adds some complication we'd prefer not to go down.  Anyone have an ETA?

**Comment by mweinand** [comment]
Crickets....

**Comment by anguslees** [comment]
> Crickets....

I can't answer what I don't have an answer to :/

sealed-secrets is not a commercial product for Bitnami, so it gets time from me when I find gaps around other priorities.  I wish it were otherwise, but that's the reality at present.

I have held off on cutting a release, because the fix for #92 is going to involve changing the schema again from what was introduced with #87 , and I want to limit the churn for users to only one new schema.  I too thought I would be able to complete the fix for #92 many months ago, and am also frustrated by the poor experience this is providing to sealed-secrets users.

**Comment by mweinand** [comment]
Appreciate the effort and understand the time issues.  Thanks for the update.

**Comment by JessieAMorris** [comment]
Any update on this? The last release was clear back in March. I know this isn't high priority, but it'd be nice if the release had some of the bug fixes and additional features that building from source gives.

**Comment by julienvincent** [comment]
I would also appreciate if we can get a patch release with some of the bug fixes and mini-features. Specifically interested in getting `namespace-wide` secrets

**Comment by mleklund** [comment]
if a patch is not forthcoming, a version of the cli that allows you to use old all in one encryption by flag, or detects non-opaque secrets and handles them the old way would sure help out the workflow.

**Comment by StevenACoffman** [comment]
@mleklund Please keep in mind a new release, a patch, or a version of the cli like you describe, are all extra work for the single unpaid volunteer that has contributed this tool. If you have time to contribute to the patch, I'm sure that assistance would be welcome.

**Comment by mkmik** [comment]
v0.8.0 has been released
