### ISSUE TITLE
Go Get fails with "constraints exclude all Go files"

### ISSUE THREAD

**Issue by rufreakde** [bitnami-labs/sealed-secrets#1066]
**Which component**:
[The name (and version) of the affected component (controller or kubeseal)](https://pkg.go.dev/github.com/bitnami-labs/sealed-secrets/pkg/apis/sealed-secrets/v1alpha1#SealedSecret)

**Describe the bug**
Trying to include the types of bitnami sealed secret since we read the secrets dynamically in an custom operator. We use kubebuilder.

**To Reproduce**

1. go get github.com/bitnami-labs/sealed-secrets

finding module for package github.com/bitnami-labs/sealed-secrets package github.com/bitnami-labs/sealed-secrets: build constraints exclude all Go files 

**Expected behavior**
Expecting the vscode plugin to understand the dependency
![Screenshot 2022-12-09 at 13 10 08](https://user-images.githubusercontent.com/28104368/206699653-d287e58b-6818-40da-bee6-419dfb787da1.png)

**Version of Kubernetes**:
(none) but go version 1.19.3

go mod setting: `go 1.19`

**make**
```bash
make
...
no required module provides package github.com/bitnami-labs/sealed-secrets; to add it:
        go get github.com/bitnami-labs/sealed-secrets
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [generate] Error 1
```

Any ideas we do not have any build constrains defined does sealed secret needs some specific parameters? I cant find anything specific in your Makefile.

**Comment by josvazg** [comment]
Hi @rufreakde ,

The issue is that we do not have any installable or importable go code at the project root. Many projects do, but not sealed secrets. One of the reasons being that we ship both a CLI and a Kubernetes controller from the same repo.

If you were trying to install the `kubeseal` binary you would need to do this instead:

```shell
go install github.com/bitnami-labs/sealed-secrets/cmd/kubeseal@latest
```
Basically you need to include the path to the code you actually want, i this case the `kubeseal` command main package folder.

Note you can chose to replace `latest` with the actual existing version you want.

To install the controller binary, which would not be very useful on its own, again it will be adding the proper path:
```shell
go install github.com/bitnami-labs/sealed-secrets/cmd/controller@latest
```

From your text, I am guessing you do not want to install binaries, but to import sealed secrets code as a library to work with it. In such case, it is again the same trick, **just add the actual path to the code you need**.

For example, if you want to call `ValidateSealedSecret` which lives at `pkg/kubeseal/kubeseal.go` you would need to use the import path `github.com/bitnami-labs/sealed-secrets/pkg/kubeseal`.

In general you would need to get something under any the pkg subfolders `github.com/bitnami-labs/sealed-secrets/pkg/...`

If you are using modules, setting that path in your code imports and doing `go mod tidy` or `go mod vendor` should do the trick and add the proper files your go.mod/sum files.

Please, let me know if this resolved your issue.

**Comment by rufreakde** [comment]
Thanks for the clarification!
What I did:
```bash
go get github.com/bitnami-labs/sealed-secrets/pkg/kubeseal
```

```go
import { bitnami "github.com/bitnami-labs/sealed-secrets/pkg/kubeseal" }
// and
...
bitnami.ValidateSealedSecret()
```

Had to write it as above and then one
```bash
go mod tidy
```
And `make` worked! :)

The vet is failing but this is to be expected since I did not pass correct arguments. Thank you very much! :)
```bash 
go vet ./...
# Unified-Provisioning/infrastructure-operator/internal/vault-client
vet: internal/vault-client/client_test.go:37:33: not enough arguments in call to bitnami.ValidateSealedSecret
        have ()
        want (context.Context, kubeseal.ClientConfig, string, string, io.Reader)
make: *** [vet] Error 2
```

Perfectly clear and direct Answer! :)
