### ISSUE TITLE
Questioning wisdom of making ciphertexts public.

### ISSUE THREAD

**Issue by leg100** [bitnami-labs/sealed-secrets#109]
This looks like a very convenient way to version control secrets.

However, I question the wisdom of suggesting to users it's safe to make the resulting ciphertext public. From your README:

> Encrypt your Secret into a SealedSecret, which is safe to store - even to a public repository. 

> mysealedsecret.json is safe to upload to github, post to twitter,

This is counter to the principle that ciphertext be restricted to the smallest possible audience, lest a weakness be later discovered in the cipher, or if the keys were to be made public.

At least, I think, it would be responsible to explain this to users and for them to then to weigh up for themselves the tradeoff of risk versus convenience with regard to their particular use-case.

As it is, it seems flippant to suggest users they can "post to twitter" the encrypted secrets (not sure why they would ever want to do this).

**Comment by anguslees** [comment]
I agree with your general point about defence-in-depth.  However, the goal of sealed-secrets is precisely to turn Secrets into a form that is as "safe" to expose as the rest of your k8s configuration - so it can be used by (eg) open organisations that manage configuration by publicly readable git repositories.

If you have a suggestion, I would welcome some text for the README that communicates a more nuanced level of concern here.  Perhaps we talk about the dangers of future-exploits (as you suggest), and then recommend users make the SealedSecret as available as the rest of their config?  (ie: a paranoid organisation also wouldn't make their infrastructure setup details generally available, whereas an open-by-default distributed/transparent community project might choose to do so)

Regarding forward-secrecy, my hope with SealedSecrets was that it would _encourage_ faster password rotation, since it enables automated "write-only" pipelines.  I don't know of anyone who has actually done this using sealed-secrets however (and password rotation is generally an issue across our industry).  Again, I would welcome some text for the README to talk about the importance of this too (or more specific bugs/PRs to better enable this use case).

**Comment by anguslees** [comment]
I don't there are action items here, closing.
