### ISSUE TITLE
Unseal sealed secret without sealed secret controller

### ISSUE THREAD

**Issue by suxiaoxiaomm** [bitnami-labs/sealed-secrets#1115]
Hi experts,
Our projects are trying to use sealed secrets.
While we are wondering whether we could unseal the sealed secret without deploying controllers.

I checked there is [HybridDecrypt](https://github.com/bitnami-labs/sealed-secrets/blob/v0.19.5/pkg/crypto/crypto.go#L76) and [HybridEncrypt](https://github.com/bitnami-labs/sealed-secrets/blob/v0.19.5/pkg/crypto/crypto.go#L36) function from package : github.com/bitnami-labs/sealed-secrets/pkg/crypto.
And I decided to implement a utility based on above functions to do the seal and unseal secrets. Also manage the public and private key by ourselves.

Is there any concerns for above solution? 

Appreciate your help!

**Comment by agarcia-oss** [comment]
Hi @suxiaoxiaomm it seems that you don't intend to use any of the Sealed Secrets components in your solution, neither the Kubernetes controller nor the `kubeseal` cli, is that correct? 

In a case like that, where you want to build your own custom encryption solution, It might be more useful to use [SOPS](https://github.com/mozilla/sops) instead. If you donñt mind, I'll close the issue since it does not seem to be related to Sealed Secrets. 

Regards!
