### ISSUE TITLE
Unable to create sealed secret without cluster-admin privileges

### ISSUE THREAD

**Issue by suculent** [bitnami-labs/sealed-secrets#112]
I'd like to allow users to create sealed-secrets in their own namespaces
I successfully created a manifest file "my-sealed-secret.yaml" with kubeseal:
```
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {  "name": "mysecret",  "namespace": "myns"  },
  "spec": {  "encryptedData": {  "passwd": "xxx"  }  }
}
```
but when I try to create it with `kubectl create`, I get an error:

> Error from server (Forbidden): error when creating "my-sealed-secret.yaml": sealedsecrets.bitnami.com is forbidden: User "system:serviceaccount:myns:tom" cannot create sealedsecrets.bitnami.com in the namespace "myns"

How can I make it work for a user who is not a cluster-admin? 
Thanks

**Comment by panatl** [comment]
You can update the RBAC to allow non-cluster-admin role to create in a given NS.

**Comment by tomasji** [comment]
Ok, but how can I find out what exactly is required in terms of apiGroups, resources, resourceNames, verbs and what namespace (myns or kube-system) to bind?
Is there any documentation or example?

**Comment by anguslees** [comment]
> how can I find out what exactly is required in terms of apiGroups, resources, resourceNames, verbs and what namespace (myns or kube-system) to bind

As with other resources, the RBAC error message tells you (emphasis mine):
> Error from server (Forbidden): error when creating "my-sealed-secret.yaml": sealedsecrets.bitnami.com is forbidden: User "system:serviceaccount:myns:tom" cannot **create** **sealedsecrets**.**bitnami.com** in the namespace "myns"

This means this particular operation needs:
```yaml
apiGroups: ['bitnami.com']
resources: ['sealedsecrets']
verbs: ['create']
```

Of course in practice you will probably want additional verbs (eg: `['get', 'list', 'watch', 'create', 'patch', 'update', 'delete']`), depending on your desired policy.

The namespace from this error message is also obviously `myns`.  `create` doesn't have a `resourceName`, but the RBAC error from other operations also includes the resource name in the error message too.

I can add some specific instructions for writing sealedsecrets RBAC rules, but I feel this would just end up being a poor duplication of the [standard k8s RBAC docs](https://kubernetes.io/docs/reference/access-authn-authz/rbac/).

@suculent To your original question: You need to add some RBAC rules that allow this operation.  You probably want to look at your existing policies for `secrets` and create similar policies for `sealedsecrets` (but you can be more liberal with "read" operations if you wish, since `sealedsecrets` don't contain the plaintext).  This will probably require cooperation from the cluster admin, if that is not you.

**Comment by suculent** [comment]
Hi,
the following c.r. seems to do the job:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-management
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "patch", "delete", "create"]
```
Thanks for your help!

**Comment by ryancastle** [comment]
Using aggregation rules to define a ClusterRole that propagates to `edit/admin` roles. See https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles

    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
      name: sealedsecrets-edit
    rules:
    - apiGroups:
      - bitnami.com
      resources:
      - sealedsecrets
      verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
