### ISSUE TITLE
"crypto/rsa: decryption error" when combining several SealedSecrets into one ?

### ISSUE THREAD

**Issue by renaudguerin** [bitnami-labs/sealed-secrets#113]
I'd like to combine several (sealed) secrets into one.

Since the values are now encrypted individually, I naively thought that all it would take would be to copy/paste the key/encrypted value pairs in the existing SealedSecrets' `encryptedData` and make a new one from that ? It doesn't seem to work :

```2018/09/04 16:00:22 Updating test/external-services-credentials
2018/09/04 16:00:22 Error updating test/external-services-credentials, will retry: crypto/rsa: decryption error
2018/09/04 16:00:22 Updating test/external-services-credentials
2018/09/04 16:00:22 Error updating test/external-services-credentials, will retry: crypto/rsa: decryption error
2018/09/04 16:00:22 Updating test/external-services-credentials
2018/09/04 16:00:22 Error updating test/external-services-credentials, will retry: crypto/rsa: decryption error
2018/09/04 16:00:22 Updating test/external-services-credentials
2018/09/04 16:00:22 Error updating test/external-services-credentials, will retry: crypto/rsa: decryption error
2018/09/04 16:00:22 Updating test/external-services-credentials
2018/09/04 16:00:22 Error updating test/external-services-credentials, will retry: crypto/rsa: decryption error
2018/09/04 16:00:22 Updating test/external-services-credentials
2018/09/04 16:00:22 Error updating test/external-services-credentials, giving up: crypto/rsa: decryption error
E0904 16:00:22.589255       1 controller.go:156] crypto/rsa: decryption error
```

Is the encrypted data somehow tied to the original metadata.name, or anything like that which would prevent me to do what I'm trying to do ?

Thanks

**Comment by renaudguerin** [comment]
After a bit more digging, it does seem like the encryptedData depends on metadata.name 😞 
Is there a security reason for that ?

**Comment by c-knowles** [comment]
One use case to allow the names to change is covered by https://github.com/bitnami-labs/sealed-secrets/issues/89. The reason is in the readme although not sure why it’s the name as well as the namespace given most security restrictions are at the namespace level.

**Comment by anguslees** [comment]
It's namespace+name because that matches the level that can be described with RBAC policies.  We could certainly invent a namespace-only variation, as is described in #89.

@renaudguerin: I tried to call out the fact that the SealedSecret is tied to a specific namespace+name in the README.md, with some mention of the attack that this protects against.  Patches to the docs would be gratefully accepted if there's something we can add that would have made this clearer for you.

**Comment by akrueger0602** [comment]
@renaudguerin @anguslees How do I recover from this error please? When I try to delete my failed secret, kubectl says it doesn't exist. When I try to recreate it, it says it does :(

**Comment by jjo** [comment]
@akrueger0602 can you give more details, if possible:
* CLI+args you're using, together with the errors you're getting
* controller log tails (`kubectl logs --tail=20 -n kube-system -l name=sealed-secrets-controller` )
Of course, please obfuscate above details as needed.

**Comment by akrueger0602** [comment]
I tried to create a secret for our cloudwatch exporter which has 2 fields in it. This is the yaml file:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudwatch-exporter
  namespace: monitoring
spec:
  encryptedData:
    access_key: ANOTHERLONGENCRYPTEDVALUE
    secret_key: LONGENCRYPTEDVALUE
```

I'm running `kubectl create -f cloudwatch-exporter.yaml` to create it.
```
$ kubectl create -f cloudwatch-exporter.yaml 
sealedsecret.bitnami.com/cloudwatch-exporter created
```

Then I see this in the logs:
```
2019/08/12 18:15:57 Updating monitoring/cloudwatch-exporter
2019/08/12 18:15:57 Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error
2019/08/12 18:15:57 Updating monitoring/cloudwatch-exporter
2019/08/12 18:15:57 Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error
2019/08/12 18:15:57 Updating monitoring/cloudwatch-exporter
2019/08/12 18:15:57 Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error
2019/08/12 18:15:57 Updating monitoring/cloudwatch-exporter
2019/08/12 18:15:57 Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error
2019/08/12 18:15:57 Updating monitoring/cloudwatch-exporter
2019/08/12 18:15:58 Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error
2019/08/12 18:15:58 Updating monitoring/cloudwatch-exporter
2019/08/12 18:15:58 Error updating monitoring/cloudwatch-exporter, giving up: crypto/rsa: decryption error
E0812 18:15:58.123915       1 controller.go:156] crypto/rsa: decryption error
```

If I try to delete the secret, I get this:
```
$ kubectl --namespace monitoring delete secret cloudwatch-exporter
Error from server (NotFound): secrets "cloudwatch-exporter" not found
```

If I try to recreate it with the annotation `sealedsecrets.bitnami.com/cluster-wide: "true"` (thought this might help after reading a few GitHub issues on this) I get this:
```
$ kubectl create -f cloudwatch-exporter.yaml 
Error from server (AlreadyExists): error when creating "cloudwatch-exporter.yaml": sealedsecrets.bitnami.com "cloudwatch-exporter" already exists
```

Don't know where to go from here :(

**Comment by Crevil** [comment]
As the controller have failed to create a kubernetes secret, there is non to delete. That is why the `kubectl delete` command fails.

And further explains why recreating the `SealedSecret` fails as it already exists.

Try deleting the `SealedSecret` and recreate it.

```
$ kubectl --namespace monitoring delete sealedsecret cloudwatch-exporter
$ kubectl create -f cloudwatch-exporter.yaml 
```

**Comment by anitakrueger** [comment]
Thank you @Crevil . That worked!
Now, why does this work when `cluster-wide` is set to True?

**Comment by mkmik** [comment]
@anitakrueger did you modify the namespace field of the sealed secret after you have sealed the secret? Kubeseal takes the namespace of the secret it gets via stdin (or the --namespace flag) into account when sealing the secret. This is a safety feature because in many RBAC setups some users might not have rights to read secrets in namespaces they don't own but can access secrets from namespaces they own.

If sealed secrets didn't enforce this, you could take a sealed secrets resource from a git repository of somebody that runs workloads in some other namespace of a cluster you have access to, change the namespace, create it in a namespace you own and finally read the decrypted secret from your namespace.

The cluster-wide annotation relaxes this check and thus if you use it you must be aware of the trade-offs.

**Comment by akrueger0602** [comment]
@mkmik I did :( I had forgotten to include the namespace in the json that I originally created with kubectl and then added it to the yaml after running kubeseal.
I'm sorry, much confusion on my part it seems.

If this is all described in the docs (that I obviously missed, sorry), then we should maybe close this issue with a link to the documentation?

**Comment by Crevil** [comment]
It is documented in the [first phrase of the `Usage` section in `README.md`](https://github.com/bitnami-labs/sealed-secrets#usage).

> Note the SealedSecret and Secret must have the same namespace and name. This is a feature to prevent other users on the same cluster from re-using your sealed secrets

If we could somehow know that this is the reason for the above error messages, it would be nice to indicate it in the logs. Something like below:

```
Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error: namespaces not aligned
```

**Comment by mkmik** [comment]
Yeah let's keep this open (or create a new one?) until we ensure that this scenario is obvious from the logs, events (e.g. kubectl describe) and the output of `kubeseal --validate`

**Comment by anguslees** [comment]
Fwiw, the current code is deliberately careful to *not* be "helpful" in
decryption errors, since this extra information could be used by an
attacker to (eg) brute force the correct namespace.

Having said that, this is the number one most common user error by a long
way, so anything we can do to make it clearer would be great.  Docs clearly
aren't a sufficient solution.

**Comment by Crevil** [comment]
Good point @anguslees . We could have the error indicate that it is either a key or namespace issur. This way we don’t give away clues for attacks but can still guide users. Something like:
```
Error updating monitoring/cloudwatch-exporter, will retry: crypto/rsa: decryption error: namespaces not aligned or wrong key
```

It’s not pretty, but something in the likes of it?

**Comment by mkmik** [comment]
Hi Gus! I'm not convinced this is private information. After all if the sealed secret resource is correct it contains the namespace in the metadata.

Imagine we encode the namespace in clear to each encrypted data item. That would help us detect when the user manually altered the resource namespace without resealing.

**Comment by anguslees** [comment]
The metadata in the sealed secret is purely informational. It is not used
during actual unsealing. It doesn't even exist at the new per-key level
either...

**Comment by mkmik** [comment]
> It doesn't even exist at the new per-key level either.
Which is why it can get out of sync.

Yes, the namespace can be overridden at config application time (kubectl --namespace), but it's quite common to encode the namespace in the metadata. And even if it's not, the very deploy instructions are also usually recorded in a git repo, or at least are not considered a secret.

I.e. If an attacker have access to the content of the git repo containing a sealed secret, it's likely

**Comment by anguslees** [comment]
Agreed.  With per-key encryption (in particular) we can assume the sealed secret namespace, name and key names (ie structure of the secret) are public.
