### ISSUE TITLE
Sprig support in templates

### ISSUE THREAD

**Issue by n9** [bitnami-labs/sealed-secrets#1193]
**Which component**:
Controller.

**Is your feature request related to a problem? Please describe.**
Derive password hash (bcrypt) from password (e.g. for htpasswd).

**Describe the solution you'd like**
Add sprig functions to templates.

**Describe alternatives you've considered**
I do not know any alternatives in sealed-secrets. An alternative could be to use external-secrets (https://github.com/external-secrets/external-secrets/blob/d605a5b450abb8072090ef115396f8b618aec2ec/pkg/template/v2/template.go#L138).

**Additional context**
No.

**Comment by josvazg** [comment]
Hi @n9!
Thanks a lot for your issue. We would like to understand better what use cases this sprig support will cover.

Sealed Secrets was initially conceived to safely store password as part of your regular gitops flow. The repo for a project setup or its deployment setup refers to the **secrets or keys to be used to get access to some resource**, in a way that such secret is only legible by the intended Kubernetes cluster that should enjoy such access to the secret and the resource it protects.

Key derivation and hashing functions are usually intended on the other side of the access equation: **Verification**. You store a derivation of the actual secret or key that the user or agent must posses to get access, so that if your authentication database is leaked, the actual secrets are not leaked with it. Attackers will still need to brute force the derivation algorithm to get possible password candidates that produce the derivation result hash. This means you must not encrypt key derivations on your verification database, and you would only encrypt the whole database in cloud and multi-tenant environments.

So again. Given that Sealed Secrets is designed to store and **distribute keys to get access** rather than **verify access**.

What would be the use cases of key derivation on this context?
