### ISSUE TITLE
renewing bring your own cert

### ISSUE THREAD

**Issue by naresh-naga** [bitnami-labs/sealed-secrets#1232]
**Which component**:
Contoller

**Is your feature request related to a problem? Please describe.**
Clarification

Using own cert to decrypt secrets by following bring your own cert guide. Not clear how certificate renewal process going to work.  Used helm chart to deploy pointing to existing tls secret. The chart takes only one secret name. I thought i can create another secret and add it to list of secret to look for but that is possible. What are the options?
thanks

**Comment by tewfik-ghariani** [comment]
Hi,

It is possible to manually renew the certificates by generating a new public-cert/private-key pair via `openssl`, then apply it as a secret in K8s and finally label it with the `sealedsecrets.bitnami.com/sealed-secrets-key=active` label so that it gets picked up by the controller upon re-deployment.

After that, the "v1/cert.pem" endpoint exposed by the controller will point to the most recent certificate and `kubeseal` can consume it to seal new secrets

---

1. Generate a new certificate
```
  SECRET_NAME="sealed-secrets-pub-key-$(date +'%s')"
  SEAL_PUB="${SECRET_NAME}-cert.pem"
  SEAL_PRIV="${SECRET_NAME}-priv.key"

  openssl req -x509 -nodes                               \
                    -days 3650                           \
                    -newkey rsa:4096                     \
                    -keyout "$SEAL_PRIV"                 \
                    -out "$SEAL_PUB"                     \
                    -subj "/CN=Sealed Secrets Controller/O=Team"
```
2. Create a TLS secret in k8s with the content of the certificate
```
kubectl create secret tls $SECRET_NAME --cert=$SEAL_PUB --key=$SEAL_PRIV
```

3. Label it appropriately

```
kubectl label secret $SECRET_NAME "sealedsecrets.bitnami.com/sealed-secrets-key=active" --overwrite
```

Finally, you can confirm that the new secret was picked up by the controller *after* re-deploying it
```
 $ k logs sealed-secrets-ctr-any-infra-example-nhn2h | head -n30
controller version: 0.22.0
2023/07/18 22:51:34 Starting sealed-secrets controller version: 0.22.0
Searching for existing private keys
----- sealed-secrets-pub-keys8flw
----- sealed-secrets-pub-keygqqk7
----- sealed-secrets-pub-keykhpr2
----- sealed-secrets-pub-key-1689639195
```
