### ISSUE TITLE
make installation easier (goreleaser)

### ISSUE THREAD

**Issue by scottrigby** [bitnami-labs/sealed-secrets#134]
## Problem
[Installation](https://github.com/bitnami-labs/sealed-secrets#installation) is not straightforward enough for some users.

## Suggestion
Use [goreleaser](https://goreleaser.com/) (with a homebrew option for mac users, etc). The resulting _installation_ section of your readme could then look something like [this](https://github.com/scottrigby/example-dep-no-vendor/#example-installation-instructions) (you're not using dep, so the instructions would be even simpler, although… separate issue, but it may be fun to stop including the vendor dir directly - it'd make PRs a lot easier to review when deps need to change!).

It's pretty straightforward so I'm sure you don't need help, but 'm happy to pitch in if you think that'd be fun.

CC @anguslees & @jbeda 😄 👋

**Comment by anguslees** [comment]
I agree we should switch to `goreleaser`.

In the meantime, there is now a homebrew recipe for `kubeseal`, thanks to @mellena1: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubeseal.rb

We should absolutely document that in the README installation section, because macOS users expect to be spoonfed :trollface:

**Comment by kskewes** [comment]
Had a go at a PR... don't mind github snitching on me.. :sweat_smile:

**Comment by spencerolsen** [comment]
I apologize for the dumb question, but I am on Windows 10 and don't know how to install. Any documentation I can refer to? I have not used goreleaser before, and it seems like support for it was maybe reverted? Any help would be greatly appreciated.

**Comment by kskewes** [comment]
Yes the PR was reverted and replacement submitted.
I did a release on my fork here a couple of months back. The windows kubeseal should work but it's unofficial and ymmv as I haven't used extensively.

https://github.com/kskewes/sealed-secrets/releases

**Comment by mkmik** [comment]
(sorry for the slowness on this I'm dealing with higher prio stuff first)

Now the installation instructions mention brew for macos, and we even have a badge that should indicate how much the homebrew release lags behind out latest github release:

[![](https://img.shields.io/homebrew/v/kubeseal)](https://formulae.brew.sh/formula/kubeseal)

@scottrigby, do you think it still makes sense to have a tap now that we have a formula in the main repo? I'm not very familiar with brew (despite being a macos user myself). Would a tap allow us to release (almost) atomically with the main release?

I noticed that the binary installed with `brew install kubeseal` is not the actual build artifact we release; it appears to be built by somebody else, likely just with  `go build` since it doesn't have the `version` variable filled it by the linker flag (which would happen if you run `make`)

```bash
$ kubeseal --version
kubeseal version:
``

What are the other practical differences?

**Comment by juan131** [comment]
We adopted Goreleaser at https://github.com/bitnami-labs/sealed-secrets/pull/668
