### ISSUE TITLE
Improve documentation about how namespacing is handled

### ISSUE THREAD

**Issue by johnraz** [bitnami-labs/sealed-secrets#136]
## Purpose of this issue:

This issue was created following @anguslees's suggestion in https://github.com/bitnami-labs/sealed-secrets/issues/120#issuecomment-454290250.

Acording to the comment linked above, there seems to be a lot of confusion around how the secrets namespacing works.

The goal of this issue is to aggregate all the comments / questions / suggestion that could help improve the readme to clarify the situation.

## My proposal:

Add a "use-case" section describing every known case by providing the sealed secret configuration, a sequence of commands (+ detailed yaml manifest if needed), result of the commands and impact on the cluster regarding who has access to what.

Something like:
Configuration context:
.... (describe sealedsecret config used)
Commands:
- `kubectl secret...`
- `kubeseal ....`
Impacts:
- secret is visible in namespace X and not in namespace Y

We could also complement that with some kind of matrix explaining what would result in what.

I'm not confident I can foresee all the use case that sealed secret covers yet so please don't hesitate to add comments or even edit my description.

**Comment by mellena1** [comment]
Thanks for making a new issue @johnraz.
And ping to @anguslees for my explanation on this issue.

I did some more research on how the crypto is currently implemented and I think I understand it a little better now. I don't work at the company that wanted the use case that I had posted in #120 anymore (it was an internship), but I do still think it is a valid problem. I think what I had in mind may have been talked about in other issues as well.

I think my idea for namespace based keys was that I wanted devs on projects to have access to a private key specific to their project so that they would easily be able to edit their secrets under the GitOps strategy. The assumption made here is that the devs don't have access to the cluster, but they can make their own changes on the git repo and PR them.

Currently, this doesn't work because the same key pair is used to encrypt all secrets on the cluster. Therefore, if I have the private key, I can decrypt all secrets in the repo. Having the namespace and name as the labels in the RSA-OEAP encryption stops people from creating that sealed-secret on their namespace and having the controller decrypt it so they can read it, but doesn't stop anyone from decrypting it manually if they have the key (as the OEAP label is public information).

So essentially you would have a key pair per namespace and you could give the dev team that private key so they could decrypt and edit the secret locally.

Hopefully that makes sense.

On a side note, do you think adding a `kubeseal edit sealed-secret.json` command to the client would be cool/useful? I'm thinking of something similar to [ansible-vault's](https://docs.ansible.com/ansible/latest/cli/ansible-vault.html) implementation where it would pop open an editor in the cmd line with the file unencrypted (ideally base64 decoded as well) and then encrypt it back on save. I might try to implement something like that in the kubeseal tool if you think that is something that fits into the ideals/roadmap of this project.

**Comment by c-knowles** [comment]
There might be a bit of overlap with https://github.com/bitnami-labs/sealed-secrets/issues/95 regarding the idea of an edit command. What do we think about exposing any private keys to users? Do they need to be able to see the current clear text value for a particular key or is an update operation on a single key within a secret enough?

**Comment by johnraz** [comment]
I strongly believe that the private key should stay private and only accessible to a few people with elevated permissions, it shouldn’t be disclosed to dev teams.

I don’t understand why the dev team would need the private key to decrypt anything as that can be done by the controller for them. 

If you don’t disclose the private key everything works as you would like: team A can read/update secrets from namespace A but not from namespace B / team B.

That’s something my plan of explaning use cases would cover. 

Also please let’s try to not hijack the thread with discussion about new feature (like edit) but only focus on the doc side of things.

**Comment by mellena1** [comment]
Yeah sorry, I didn't mean to hijack the thread.

I definitely think a use case section in the docs would be valuable. I think the docs give a lot already on how to use the tool in a basic sense, but giving a sort of standard procedure for using the tool in a GitOps strategy would be great. I also don't know if I am knowledgable enough on what happens in each case to be able to write the docs here.

As for giving the private key to devs, I do personally still see value in it. You can do it the way you describe @johnraz, but that is under the assumption that you want to give all of your devs access to the cluster. I think depending on the organization, this may or may not be the direction they want to go in (even if it is only read only access). My personal view on it is that the devs can deploy everything else in the GitOps flow without having access to the cluster, why should secrets be any different? This is also starting to feel out of scope of the issue, so maybe we could discuss this back in #120?

**Comment by johnraz** [comment]
I still don’t understand why you want to give the secret key away to achieve that. The public key is enough for a dev to create a sealed secret to a git repository and have that secret added to the cluster in a gitops fashion. They don’t need to have access to either the cluster or the private key.

**Comment by mellena1** [comment]
They can add a new secret, but they can't edit an existing one without the private key or cluster read access to secrets. I know some projects use secrets as essentially files (json, yaml, etc) that get mounted into the pod, so all of your key-value pairs would be encrypted (whether or not this is good design is a different story). So in this case you can't easily change a value without decrypting the entire string. Even with individually encrypted key pairs in a sealed secret, it is still potentially annoying not being able to see what the values are set to before you make and encrypt a new one.

**Comment by johnraz** [comment]
When talking about security and safety of secrets, design is key.
To me, giving access to the secret key is way more of a bad move than giving read access to a cluster namespace. I never argued that editing secrets was not useful. My point is not to prove that the “edit” use case doesn’t exist but more that we should make sure that people keep their secret key, secret. A few questions that raises with sharing the secret: How do you share it? Where do you store it? You’d need to give access to the cluster to the dev who needs it so they can fetch it? To a special place where dev can read stuff outside of the cluster? It all sounds that this would broaden the attack surface and also increase the complexity of your platform. Giving read access to the cluster is way less of an issue. And if you need to keep things separated on the cluster, name spacing is probably the way to go. I do agree that the “edit” feature would be nice and could include some kind of RBAC on its own to restrict access to some secrets only. But that wouldn’t happen by sharing the secret key.

**Comment by mellena1** [comment]
I definitely don't disagree here. I think being able to let the controller do everything is absolutely more secure (smaller attack surface like you said). I could see some still wanting the option to use the private key to edit though. I know for my team that I previously worked with they would have preferred using the key, as they had secret sharing systems in place already and wanted to restrict access to the cluster as much as possible. You could argue that that isn't the right way forward (and I wouldn't entirely disagree).

I think how they share the secret and where to store it is up to them to figure out. This is essentially how ansible-vault's implementation works, you have a password that you keep secret and share to the people that need to edit the file, but they also don't have a controller always running so that is the only option.

Just wanted to share a possible use case. I don't work with that team anymore, so I don't necessarily have any reason to request this anymore, I just wanted to get that idea out there for them. (I would, however, really like to see an edit feature for my own personal use).

But I think we are far off topic now, so we may need to put this discussion on the back burner. Sorry for starting this conversation in the wrong spot, I didn't think about the scope of this topic originally :)

**Comment by johnraz** [comment]
No problem at all I think it is sane to share on those topic, even in the context of the doc. To think about what and how others handle this 😊
