### ISSUE TITLE
Manual unsealing and automation

### ISSUE THREAD

**Issue by moh-abk** [bitnami-labs/sealed-secrets#144]
In the blog post on `sealed-secrets` it's made to look very easy to integrate and automate but a few issues prevent this from being a reality;

- a good workflow is having a `secrets.yaml` file that contains all your secrets, you can then encrypt it with `kubeseal` and commit to git
- when you need to add more secrets you should be able to unseal it, add secrets and reseal it and `kubectl ..` it back to the cluster

this is how systems like Ansible vault work. 

- is there plan to add an `kubeseal unseal` command?
- or update the `kubeseal` cli to allow creation of multiple secrets that get dumped to a file without relying on `kubectl`?

**Comment by anguslees** [comment]
There are no plans to add an `unseal` command, and this would be counter to the asymmetric encryption design.  You can of course just read out the decrypted Secrets from the cluster, assuming you have that level of RBAC access.

You can trivially create additional SealedSecrets, by just creating new ones and appending them to an existing yaml file.  I think what you're asking for instead is to be able to add new encrypted values to an *existing* SealedSecret.  This is precisely the goal of the v0.7.0 "per-key encryption" change.  See [the release notes](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.7.0) for details - it works, but is very poorly documented and still has some rough edges (in particular, the `kubeseal` tool should make it easier to just encrypt a single value).

Please have a look at the v0.7.0 changes, and let me know if they meet your requirements.  Future releases will move further towards this design (and drop the "whole Secret" approach of earlier `kubeseal` versions)

**Comment by anguslees** [comment]
@moh-abk Did my earlier reply make sense at all?

1. You _can_ just incrementally add/replace secret values in an existing SealedSecret, without needing to decrypt the existing values.  See the "per-key encryption" release notes I pointed to.

2. If you ever need to "unseal" a secret, the easiest is to just read the decrypted Secret from the cluster.  In particular, this gives kubernetes the chance to verify via RBAC that you are actually allowed to read the Secret values.  At this stage I have no plans to offer an additional method to do an "offline unseal", precisely because it would mean I then have to reimplement all the access policy, auditing, etc that RBAC already provides.

**Comment by dimitrovvlado** [comment]
@anguslees does it make sense to do the decryption inside of a running pod? Not sure how to approach that as I'm fairly new to the controller, but the use-case would be to keep encrypted files as resources in the source code (such as private keys etc) and decrypt them at application runtime. 
Passing all secrets as config maps is not always a good approach especially if those are quite big in size.

**Comment by mariusmarais** [comment]
@dimitrovvlado You may want to consider generating and storing a "Key Encryption Key" as a sealed secret, retrieving that via ENV and using it to decrypt your large secret in the application code. It's more manual steps, and sealed secrets won't handle everything for you, but it is very flexible.

**Comment by bitspike** [comment]
Hello, this feature would be very nice to have. I am a k8s cluster administrator and I have a system which performs security checks on Git committed resources while the cluster is unavailable. Right now my solution is to have a custom script which decodes the sealed secrets (using the private key) out-of-cluster and perform the checks on the values.

Since this mechanism will "break" if you change your encryption method, a decrypt method on the sealed-secrets binary (so that I cloud decrypt using a sub-process) would be really nice.

alternatively a source code "contract/guarantee" would also be great e.g. "decryption method HybridDecrypt in sealed-secrets code will always have the current signature and will be in the same package". This way I could base my system on your code base.

**Comment by juan131** [comment]
There's a supported way to decrypt an secret, see:

- https://github.com/bitnami-labs/sealed-secrets#can-i-decrypt-my-secrets-offline-with-a-backup-key
