### ISSUE TITLE
Proposed --raw flag for encrypting individual data

### ISSUE THREAD

**Issue by tmlbl** [bitnami-labs/sealed-secrets#162]
We are looking to adopt sealed-secrets but hesitant because the tool requires an entire secret object as input. This means that developers must either:

- Write out the secret in YAML, unencrypted and in plain text, and then pipe it through the tool to create a sealed secret. If they want to update it later, they have to do this process again, so they will likely just keep the original secret file around on their hard drive
- Create a traditional secret in a Kubernetes cluster, then read it back out and create a sealed secret. They must keep the original secret around in case they want to update it and seal it again.

We prefer not to store secrets at all on developer machines or lower-level environments if possible, so I am working on extending `kubeseal` to support the following use case:

As a developer, I can write out a yaml definition of a `SealedSecret` in my source code:

```yaml
apiVersion: bitnami.com/v1alpha1
type: Opaque
kind: SealedSecret
metadata:
  name: my-secret
spec:
  encryptedData:
    databasePassword: ''
```

I can then encrypt individual items to put in here with only the public key and the secret namespace/name

```bash
echo "trustno1" | kubeseal --cert cert.pem --raw --namespace myns --name my-secret
```

This outputs the base64-encoded value to add to `encryptedData`. Thus I have managed to create a `SealedSecret` without ever saving the secret value to my hard drive or having sent it to a shared cluster.

**Comment by mkmik** [comment]
it seems that your issue is two-fold:

a) the need to keep secrets around for later in order to update them
b) the risk of storing a k8s secret yaml on disk as a temporary file

a:

since v0.7.0 sealed-secrets supports per-item encryption, which means that now you can re-create a single item of the secret without having to keep the old secret around.

however, kubeseal doesn't yet come with a "merge" functionality where the new encrypted secret is update in-place. See #95 

b:

Yes it sucks. Currently it's possible but you have to do something horrible like:

```sh
$ echo supersecret | kubectl create secret generic mysecret --dry-run --from-file=foo=/dev/stdin -o json | kubeseal
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysecret",
    "namespace": "toolchain-web",
    "creationTimestamp": null
  },
  "spec": {
    "encryptedData": {
      "foo": "AgAX4....
```

again, see #95 

I _think_ we can merge this issue with #95. What do you think?

(sorry for the slow reply, we were recently acquired and got a bit distracted; we're on it now)

**Comment by tmlbl** [comment]
#95 seems to contain a more complete way to address this issue, so I'll go ahead and defer to that discussion
