### ISSUE TITLE
Clarification regarding Private key renewal

### ISSUE THREAD

**Issue by linuxbsdfreak** [bitnami-labs/sealed-secrets#256]
Hi,

As per [RELEASE-NOTES](https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#v090-draft)

In the *Private key renewal* section.  If the private key of the sealed-secrets controller is rotated every 30 days. Do i need to re-generate the sealed secrets  for a given secret every 30 days?  I presume not since the encryption of a secret is done using the public key. If both the pub and private are regenerated every 30 days then  i say i need to regenerate it. Could you clarify the workflow. ?

Regards,
Kevin

**Comment by mkmik** [comment]
A private key cannot be changed without also affecting its public key. That said, we're not replacing the key, we're adding a new key every 30d.

The release notes state out explicitly that you don't have to update old secrets. From the notes:

> This release turns on an important security feature: a new private key will be now created every 30 days by default. Existing sealed-secrets resources will still be decrypted until the keys are manually phased out.

Perhaps the wording is not clear enough, I'll try to improve (and CC you for a review :-) )

It's important to understand why are we renewing the sealing keys in the first place:

There is one thing that makes reasoning about sealing keys a bit confusing: sealed secrets works in the opposite direction than your average secrets.

Take for example your ssh private key: you use that to prove to a server that you can access and it's a good practice to regularly rotate that key. Which means, you will generate a new one, and the server will stop accepting your old one (by no longer trusting your old public key).

In sealed-secrets we're not using the sealing key to control which secrets can be written to k8s. It's not access control. There is nothing inherently dangerous in unsealing a secret created with a key that was issued last year.

What's dangerous is to leak the sealed-secret private key. If (when) that happens, all of the secrets sealed with it are compromised. We assume that all of the encrypted sealed secrets are by design public data (for some definition of public, but in any case the encrypted value are not secrets and are not treated as such). Thus you ultimately don't have control over them. They could have been copied, archived etc.

What you need to do is to rotate the actual values you have encrypted in the first place. And encrypt them again. Obviously you should encrypt them with a new "sealing key", otherwise down they go in the drain again.

---

So, a reaction to the event of knowing a key has been compromised is:

1. create a new sealed-secrets "sealing" key
2. locate all secrets sealed with that key.
3. rotate all the secrets (e.g. changing your DB password etc)
4. seal them again
5. push them to k8s

Removing a compromising private "sealing" key can help you with step (2), since now sealed secrets will complain that it cannot unseal those secrets again.

In other words, while it's not technically necessary to remove the compromised private key as long (as you don't encrypt new secrets with it) you might still want to remove it in order to detect which of your secrets are affected and/or ensure that you actually have rotated them all.

---

It's a good practice to rotate your secrets (e.g. your database passwords) periodically even if you're not aware of a leak right now.

The idea is to reduce the time window during which somebody who has observed your secret can do meaningful use of it.

However, if you add sealed-secrets to the mix you might periodically rotate your application secrets
every month but end up encrypting them using the same key. all the time.

If that key leaks you might keep rotating your application secrets for nothing, since the attacker can keep accessing your public git repo and just decrypt the new application secrets.

---

Thus, the sealed-secrets controller will now periodically create new sealing keys, to reduce the time window during which somebody how has had access to such a key can decrypt your application secrets.

**You are still responsible for actually generating new application secrets**

That's why we renamed `--rotate` to `--re-encrypt`, because `--rotate` gave the impression to many people that the secret was now safe to be used even in the event of a compromised sealing key.

In other words, a compromised sealing key retroactively affects any secret you have encrypted with it. No amount of re-encryption and forgetting of the original key on your part can change that.

---

We're not enabling automatic deletion of old encryption keys because that would force everybody to rotate their application secrets. While this is a best practice, it's up to you to follow it.

**Comment by dbyron0** [comment]
Small nit/question about the above, since it's not totally clear what `that key` is in number 2.  Seems like it could be the new key created in number 1 or the compromised key...and I think you mean the compromised key.

**Comment by mkmik** [comment]
@dbyron0 yep thanks; edited in-place.

**Comment by linuxbsdfreak** [comment]
@mkmik . Thanks for the explanation. 

-  Is it possible to disable creation of a private key every 30 days? Since i will not be using this feature for the moment. We have lots of secrets which will need to be re-encrypted.
- When a new private key is created every 30 days. How do i get the related public key for re-encrypting a secret?

Regards,
Kevin

**Comment by mkmik** [comment]
You can disable the renewal if you want.
But you don't have to.

Re-encrypting your old secrets is not at all necessary unless you also plan to get rid of the old private keys (which doesn't happen automatically)

If your private key leaks, you should treat all the secrets encrypted with it as potentially compromised. Re-encrypting them with a new key won't change that fact.

The advantage of key renewal is that **new** secrets will be encrypted with a new key and thus an attacker that only has the leaked key cannot decrypt all future keys.

This is particularly important since it's a good practice to rotate your application secrets on a regular basis. But if you rotate your secrets and then encrypt them with a potentially compromised key you'd negate the benefit of rotating your application secrets in the first place.

**Comment by mkmik** [comment]
W.r.t the helm chart, I didn't have time to ping the helm chart maintainer nor to help with the changes. Help is welcome

**Comment by bartcee** [comment]
Hi @mkmik, This thread greatly improved my understanding of how sealed secrets work. Could you please let me know what label would an expired key has. The active one will always be
`"sealedsecrets.bitnami.com/sealed-secrets-key": "active"`
What does "active" change to after 30 days on an expired key?

**Comment by mkmik** [comment]
They stay "active". Sorry this label is a bit confusing.

**Comment by cep21** [comment]
@mkmik I didn't want to just emoji up https://github.com/bitnami-labs/sealed-secrets/issues/256#issuecomment-531306243

I think it's a really good summary of the philosophy of encryption with sealed-secrets and should get a section in the docs.

**Comment by mkmik** [comment]
Ah yes, in fully aware that this should feature prominently in the main docs, I just didn't find a way (and the time) to do it right. I'd like to strike a good balance between depth and clarity.
Help is welcome. In any case, thanks for refreshing my attention on this topic.
