### ISSUE TITLE
Confuse with certificates renewed

### ISSUE THREAD

**Issue by Renz2018** [bitnami-labs/sealed-secrets#291]
Since v0.9.x certificates get automatically renewed every 30 days. 
If I create a sealedsecret yaml before 30days
Now I use --merge-into options update part of sealedsecret data
Because I think old sealedsecret use old cert encrypt secret data

**Comment by mkmik** [comment]
Are you reporting a specific problem you're seeing or is this just a question?

Individual items in the same sealed secrets resource can be encrypted with different certificates. You don't have to worry about that new certificates will break old secrets (unless you manually remove the encryption keys from the `kube-system` namespace).

**Comment by Renz2018** [comment]
@mkmik Thanks for your reply.
I confuse with certificates renewed.
If I create a sealedsecret yaml before 30days,
And I  k apply -f sealedsecret.yaml after 30days
Is that decrypt correctly?
Or I must use new cert to encrypt raw secret again?

**Comment by mkmik** [comment]
renewal doesn't replace the old certificate, it creates a new one used for new secrets.
so, yes, you can do k apply -f sealedsecret.yaml after 30days and it will work

**Comment by mkmik** [comment]
The readme is explicit about this:

> The feature has been historically called "key rotation" but this term can be confusing. Sealed secrets are not automatically rotated and old keys are not deleted when new keys are generated. Old sealed secrets resources can be still decrypted.

But since this question comes up a lot I think I could use some help in phrasing this better.
I'm also not a native english speaker and generally what's clear to somebody might not be clear to somebody else. In other words, @Renz2018, could you help me by telling me how would you write it down so that you would understand it without confusion?

**Comment by Renz2018** [comment]
@mkmik , I'm also not a native english speaker too
So I read the doc again and again, I General understanding about renewal key
I still don't understand the different about Early key renewal and automatically renewed, that's have same effect?
I suggest definition of terminology(eg: key, secret) clear, add some picture or gif, and more eg, add common suitation explain?

**Comment by Renz2018** [comment]
@mkmik 
version: 0.9.2
I test the Early key renewal,
1.I create sealedsecret.yaml(use old key)
2.use label sealedsecrets.bitnami.com/sealed-secrets-key=compromised and  kubectl delete po( I use kill -SIGUSR1 1 first, but It return error)
3.I found a new secret(sealed-secrets-key) created.
4.I apply sealedsecret.yaml(from step 1) to k8s.
5.sealed secret controller's log: 
```
2019/10/14 07:35:02 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"kube-system", Name:"proj-test-secret", UID:"14b438cb-9401-4d8e-95c7-e125e351cd00", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"14725691", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (haha)
```
Is that mean early key renwal make the old sealedsecret  no use

**Comment by mkmik** [comment]
If you explicitly set sealedsecrets.bitnami.com/sealed-secrets-key=compromised then it's as if you had deleted the old key

**Comment by tehmoon** [comment]
:wave: Upon further inspection of the certificate to understand more how it works, I found that the renewal thing was also confusing. Reading the docs:
```
Sealing keys are automatically renewed every 30 days. Which means a new sealing key is created and appended to the set of active sealing keys the controller can use to unseal Sealed Secret resources.

The most recently created sealing key is the one used to seal new secrets when you use kubeseal and it's the one whose certificate is downloaded when you use kubeseal --fetch-cert.

The renewal time of 30d is a reasonable default, but it can be tweaked as needed with the --key-renew-period=<value> flag for the command in the pod template of the sealed secret controller. The value field can be given as golang duration flag (eg: 720h30m).
```
I'm thinking that the x509 certificate is only valid for `--key-renew-period`. But what I found is that, it's each `--key-renew-period` tick, it generates a certificate valid for 10 years.
I had though that the expiry time would act like gpg in the sense that the `kubeseal` client would refuse to encrypt for a expired key. Decryption can still happen because the controller is only worried about finding the right private key.
I did not find any mention of this 10 years thing except looking at the source code: https://github.com/bitnami-labs/sealed-secrets/blob/ad3e7ecbd03d8d345db202129e0081282b614ce5/cmd/controller/main.go#L43

It would be really nice if that was added to the official documentation, perhaps it would help other people too.

Good job making this awesome project!!

PS: full disclosure, I'm not a native english speaker, so please, let me know if I'm missing something.
