### ISSUE TITLE
Manual key renewal

### ISSUE THREAD

**Issue by guylabs** [bitnami-labs/sealed-secrets#298]
Hi

What we try to achieve is to be able to manually update the key on the controller and not rely on the automatic key renewal. We have our own credentials cycling process and we want to know what key pair is used to encrypt the sealed secrets.

We setup the controller with the `--key-renew-period=0` flag to disable the key renewal. We then retrieve the current key pair via [this](https://github.com/bitnami-labs/sealed-secrets#how-can-i-do-a-backup-of-my-sealedsecrets) command and store them in our infrastructure.

Now we see the following workaround to make the manual key renewal working:

1. Backup the key as described [here](https://github.com/bitnami-labs/sealed-secrets#how-can-i-do-a-backup-of-my-sealedsecrets)
2. Create a new key pair and add the Base64 encoded private and public key pair to the `tls.key` and `tls.crt` entries of the backuped `master.json`
3. Reencrypt all sealed secrets via `kubeseal --cert new-key-pair.pub --re-encrypt < old-sealed-secret.json > new-sealed-secret.json`
4. Restore the `master.json` with the new key pair, restart the controller and then push all new encrypted sealed secrets.

Would that process work or do you see a better solution? Does step 3. work with reencrypting a sealed secret with a specified certificate via `--cert`?

Thanks in advance!

**Comment by mkmik** [comment]
re-encrypt is a controller-side operation. The controller will re-encrypt the sealed secret using the latest encryption key available in the cluster.

Are you aware that the sealed-secret controller can operate with multiple keys?

Currently forcing generating a new key-pair is a bit clumsy (it requires sending a HUP signal and the docker image currently lacks the `kill` command).
In https://github.com/bitnami-labs/sealed-secrets/issues/199#issuecomment-515497780 I suggested a possible solution

**Comment by mkmik** [comment]
Would that work for you?

1. add a `renew-if-older-than` flag/env var to your controller deployment specifying the current timestamp

2. wait until the controller has restarted with this new flag/env vare

3. optionally re-encrypt all sealed-secrets with `kubeseal --re-encrypt ...` if you plan to GC your old keys.

---

That said, I'd like to better understand why do you want to re-encrypt all the existing secrets.

You mention you have a "credentials cycling process". Are you also cycling the credentials that you have sealed with sealed secrets or do you only plan to cycle the sealed-secrets encryption keys?

**Comment by guylabs** [comment]
About our credentials cycling process: Yes here we cycle the credentials that are sealed with sealed secrets and we also want to cycle the key pair that is used to seal the secrets. That is why we would need a way to manually set a new key pair, then encrypt all sealed keys with the new key and then delete the old key pair. Actually we do not need the reencrypt, as we would cycle the credentials anyway.

How does the sealed secret controller know which sealed secret to decrypt with which key? Is there an internal mapping?

I'd say having a way to set a new key and remove an old one would be best.

Wouldn't that work with the steps 1. 2. and 4. as I described it? Problem there is that it will override the current key correct?

**Comment by mkmik** [comment]
> Actually we do not need the reencrypt, as we would cycle the credentials anyway.

yep, that's the idea.

The whole point in re-newing the sealed-secrets encryption keys, is to ensure that newly encrypted doesn't leak because somebody leaked the private key in the past. In other words, it would be pointless to cycle encrypted credentials only to leak them again as soon as you seal them.

Viewed through that lens, it's apparent that what matters is the freshness of the most recent key, since that's the one used to encrypt new secrets.

Old keys are not really a problem to keep around, except for the storage space they consume on the API server. 

That's why we automatically renew the keys every 30d. It's not too frequent to create too many keys and thus too much pressure on the API server storage, but it's frequent enough so that it's likely that on average a credentials cycling process will be done using a new key.

> How does the sealed secret controller know which sealed secret to decrypt with which key? Is there an internal mapping?

There is a mapping that uses a fingerprint (hash) of the public key as index.
The idea is to prefix every encrypted data item with such a fingerprint so that we can quickly locate which key to use for decryption, but we currently didn't extend the sealed secret format to support that and hence we try to decrypt each item with every key (thus it's `O(n)` over the number of private keys). Issue #226 tracks the implementation of this optimization.

**Comment by guylabs** [comment]
Thanks for the explanation on how you map the keys to the sealed secrets.

I see your point on how you do the key renewal and that the controller also accepts old keys, but we'd like to have one key present in the controller to assure that all sealed secrets are encrypted with that specific key. This key we can then store outside of the controller to be able to decrypt any sealed secret in case we need it.

To add a new key we could basically deploy the backup of the key as described in [Step 1.](https://github.com/bitnami-labs/sealed-secrets/issues/298#issue-513381039) with a different key pair and the active label, and encrypt the new sealed secrets with that new key and at the end remove the old key. Or how are multiple keys handled? And how does the controller search for these keys? Based on which identifier?

**Comment by mkmik** [comment]
> Or how are multiple keys handled? And how does the controller search for these keys? Based on which identifier?

As mentioned in my previous comment, until #226 is implemented we literally try every private key in a loop until we find one that decrypts the secret.

This means, that you can easily:

1. create a new key (while keeping the old)
2. cycle all of your secrets
3. delete the old key
4. restart the controller and check in the logs that no secret encrypted with the old key remains

The ability of the controller to work with multiple keys allows you to perform this operation on a running cluster without downtime.

**Comment by guylabs** [comment]
Ok nice that would work for us! 

How can I create a new key and how to delete the old one? Is it enough to adapt the backup of the current key and push this as new key and delete the one of the backup ? Or does the controller need to create the new key ?

Thanks a lot for your support and your responsiveness!

**Comment by mkmik** [comment]
It's easier if you let the controller create the new key.

It's documented in https://github.com/bitnami-labs/sealed-secrets#early-key-renewal.
Currently the operation is a bit clumsy because it either requires you to disable/delete the currently active key, or it requires you to exec in the controller container execute `kill -USR1 1`, which is currently broken because we switched away from alpine linux based images towards distroless based images, which don't have the `kill` command installed (reported in  #199).

I implemented an improvement to that workflow in #299 (documented in #300), which I will release hopefully today.

You can see all the keys with:

```
kubectl -n kube-system get secret -lsealedsecrets.bitnami.com/sealed-secrets-key
```

(I assume this is also how you'll back them up)

When you're ready to delete a key just delete it with `kubectl -n kube-system delete secret ....`

**Comment by guylabs** [comment]
Ok. According to your answer we can then follow these steps:

1. Create a new key by adding the following secret to the cluster:
```yaml
apiVersion: v1
type: kubernetes.io/tls
data:
  tls.crt: Base64EncodedPrivateKey
  tls.key: Base64EncodedPublicKey
kind: Secret
metadata:
  namespace: kube-system
  generateName: sealed-secrets-key
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
```
2. Encrypt all new credentials with this new public key and override the existing ones.
3. Restart the controller to check that the new key is used for all new encryped sealed secrets.
4. Then as a last step remove the old key by executing `kubectl -n kube-system delete secret {OLD_KEY_NAME}`
5. Restart the controller again to get rid of the old key in memory.

**Comment by mkmik** [comment]
I'm curious: why so you prefer to manually create the keypair?

**Comment by guylabs** [comment]
As we need to store the private and public key, it is simpler for us to create the key pair locally, store it, then encode it to Base64 and create the key in the cluster. Additionally we use the offline encryption method of `kubeseal --cert` with the already stored public key as not everyone in our team has access to the cluster.

The other way we would need to set a flag on the controller, restart it, retrieve the key and decode the private/public key. As we use Flux for managing our cluster it would be more complicated than just creating the key manually.

So does the process work as described [here](https://github.com/bitnami-labs/sealed-secrets/issues/298#issuecomment-547566811)?

**Comment by mkmik** [comment]
> So does the process work as described here?

yep, it should work.

**Comment by guylabs** [comment]
Ok nice. Will test it and come back here such that we can close this issue.

**Comment by guylabs** [comment]
It worked as described and we can have the old and the new certificate active, do the migration to the new certificate and remove the old one. I've used the following commands to create the certificate if anyone else has the same requirements:

```
openssl req -x509 -nodes -newkey rsa:4096 -keyout $privateKey -out $publicKey -subj "/CN=sealed-secret/O=sealed-secret"
kubectl create secret tls sealed-secrets-key --cert=$publicKey --key=$privateKey -n kube-system
kubectl label secret -n kube-system sealed-secrets-key sealedsecrets.bitnami.com/sealed-secrets-key=active
```

Thanks again for the help @mkmik. Really appreciated!
