### ISSUE TITLE
Instructions for 0.9.x not clear

### ISSUE THREAD

**Issue by SystemZ** [bitnami-labs/sealed-secrets#311]
Hi, I have big trouble to understand documentation for 0.9.x.
It seems that current wording is perfect for security person but not for average user.
I hope that my questions will help simplify README or create some sort of FAQ / TL;DR doc to clear confusion for other users allowing quick start.

In my case I just wanted a tool that just encrypts secrets and then it can be safely committed to repo.
It uses some keys to encrypt it, it's understandable, so I made a backup of it to safe location to allow disaster recovery.
I started using this tool from 0.8.x and it's doing it's job great. I like it.

I've seen 0.9.x and wanted to upgrade but some parts of it changes automatically, I'm still not sure what it means to me. README is very complicated to understand (maybe it's just me?)

Normally as a cluster operator you want to know what is going on, what can go wrong and what we should do regularly in simple terms.
Especially if you need to recreate whole cluster in case of some disaster, so you basically DON'T want automatic changes because some steps to recreate cluster can stop working and it can go very wrong.

So after migration to 0.9.x do I need to...
- change my backed-up key for encryption ?
- change secrets in repo ?
- ignore some changes in encrypted secrets in tools that diffs and auto apply yamls with secrets from repo ? (argo CD)
- do all of the above steps are different after waiting default time for automatic rotation ?
- do all of the above will change in future updates ?

And bonus question...
How to modify controller yaml to keep old, no automatic behavior just in case to prevent fuckups?
There is info in README (but not in changelog with migration info) about arg for controller but there is a risk that I edit yaml wrong, my setup explodes and do some changes that I don't want. Can you provide small remark about how to apply it in yaml?

**Comment by mkmik** [comment]
it's very hard to make something that is at the same time a) simple to use for everybody b) secure c) requires no dependencies on services managed by third parties

That's the challenge sealed-secrets was facing, in particular w.r.t security defaults.

Before getting deeper in how to improve the README (because I think you do have a point: I'd really  like to make it easy to grasp by the uninitiated, and it's currently not), let me just clarify one thing:

If you want to keep the pre 0.9.x behaviour w.r.t automatic key renewal, you can do it by simply passing `--key-renew-period=0` flag or `SEALED_SECRET_KEY_RENEW_PERIOD=0` env var to the controller k8s manifest).

---

Before 0.9.x the cluster only has one encryption key. Users usually back this up once and forget about it.

If this key accidentally leaks (e.g. some of your k8s cluster users get access to read secrets in the kube-system namespace, even for a brief monent), the consequences are dire: since that key will be used for encrypting every new sealed secret, the person who had access to the encryption key once can compromise all the secrets in the cluster, even in the *future*.

This would basically render all the normal best practices around password rotation ineffective.

For example, a common best practice in organizations is to force periodic rotations of secrets such as your production database password. Let's imagine an organization has a security team that forces everybody to do that, and have a procedure in place that actually changes the password of your database. In turn, you do update your sealed secrets every time your databases password gets updated (e.g. every 6 months, a year, just an example) you think you have complied with the policy. Except, you wouldn't. The new password would be visible to to the attacker who gained access to the encryption key in the past.

This *surprise factor* is very dangerous, to the point that we thought it was better to make it slightly harder to do disaster recovery properly, rather than risking major breaches in the security guarantees.

The disaster recovery process is severely under-documented, I'll make some obvious improvements ASAP, and the rest thanks to further feedback.

That said, "all you have to do" is:

1. periodically backup:
```
kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key -oyaml >backedupkeys.yaml
```

2. copy `backedupkeys.yaml` to some secure place.

3. restore:

```
kubectl apply -f backedupkeys.yaml
```

You don't have to change any secrets in the repo. Old secrets are encrypted with the old key. Automatic key renewal is a feature that makes sense for new keys (the README explains advanced concepts like re-encryption, but we should put that in an advanced manual and simplify the main doc).

If the frequency of your back up is very frequent (e.g. daily), then you don't really have to coordinate with the controller automatic renewal. Otherwise, try to make the backup happen as close as possible to the new key generation, so that you can restore any new secret that has been created with such a key.

---

> ignore some changes in encrypted secrets in tools that diffs and auto apply yamls with secrets from repo ? (argo CD)

I don't understand; can you please elaborate on that question?

**Comment by mkmik** [comment]
> it's very hard to make something that is at the same time a) simple to use for everybody b) secure c) requires no dependencies on services managed by third parties

FWIW, we're working on integrating with several cloud provider's encryption services (KMS) and hashicorp vault (so that management of the encryption keys is somebody else's problem).
That would make it simple for everybody (a) and secure (b), at the cost of adding a dependency to a service (b) :-)

**Comment by mkmik** [comment]
fixing the [How can I do a backup of my SealedSecrets?](https://github.com/bitnami-labs/sealed-secrets#how-can-i-do-a-backup-of-my-sealedsecrets) FAQ entry to mention the multiple keys was a low hanging fruit.

**Comment by presidenten** [comment]
@mkmik I have changed SEALED_SECRET_KEY_RENEW_PERIOD=0 in env, and watched the pod restart, but it still seems to renew my keys. Have I missed something or is it a bug?

```bash
$ k -n kube-system describe deployment sealed-secrets-controller | grep -A 1 'Environment:'
    Environment:
      SEALED_SECRET_KEY_RENEW_PERIOD:  0
```

**Comment by mkmik** [comment]
Sorry on my phone but perhaps:

SEALED_SECRETS_... plural

**Comment by presidenten** [comment]
Ok! Ill try to set it to 1 and check back again tomorrow if the key has changed, then Ill verify here if it worked or not.

**Comment by presidenten** [comment]
Checked in the code and I see that `flagEnvPrefix= "SEALED_SECRETS"`, so the missing plural is probably the case though. You might want to edit you comment above to avoid others from making the same mistake as me, since I just copied the value from there.
Ill still verify tomorrow though :-)

**Comment by presidenten** [comment]
@mkmik Seems like it still wont work. I changed the value to `1` two days ago, but since I didnt see any change I waited one more day, but I still have not got any new keys. Which means that the controller still isnt respecting the environment variable `SEALED_SECRETS_KEY_RENEW_PERIOD either. Ill make a separate issue to avoid cluttering this thread.

**Comment by SystemZ** [comment]
Thanks for elaborate answer :)
To not let this issue rot, I'm closing this as solved for me.
