### ISSUE TITLE
Decrypting offline with a backup key and kubeseal throws conversion error

### ISSUE THREAD

**Issue by hkailantzis** [bitnami-labs/sealed-secrets#319]
While testing the solution, after backing up my key and trying to unseal an already deployed SealedSecret on minikube, I run the following command to unseal it. Not sure if the following is correct:

`kubectl get sealedsecret.bitnami.com/mysecret -o=yaml | kubeseal --recovery-unseal --recovery-private-key master.key --controller-namespace=default > unsealed.yaml`

The command above throws the following error:
`error: converting (v1.List) to (v1.Secret): ObjectMeta not present in src`

Any idea/hints of what I'm doing wrong ? Thanks in advance.

Kubeseal version: 0.9.5 (installed with Homebrew)
Installed latest helm chart of Sealed secrets controller (imageTag:  v0.9.1)
minikube version: v1.5.2
kubectl: 1.16.2

**Comment by mkmik** [comment]
bummer; that's because `--recovery-private-key` expects individual secrets, and not a v1.List.
The documentation mentions that all you have to do is to `kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml >master.key`, hence 
`--recovery-private-key` should parse `v1.List` objects as well
