### ISSUE TITLE
Issues with communication between kubeseal and controller

### ISSUE THREAD

**Issue by iamvyom** [bitnami-labs/sealed-secrets#347]
Hi,

I have installed kubeseal locally and the controller pod is running in the cluster. I am not getting the config file via which the kubeseal will communicate to the controller.

**Please consider me as a beginner and help  me here.** 
I have about 30 + services and each are having their own secrets and 5 environments of this structure.

Please provide your inputs on 
1. **How does kubeseal communicates with the controller ?**
2. **What is the use of controller kubernetes service ?**
3. **How and where shall i create the cerificate ?**  
4.  **If i  use kubeseal and apply the sealedsecrets in cluster, how will controller automatically unseal it and apply the same?**
5. **Please provide a sample secrets yaml file that i can seal using kubeseal (taking into consideration the point that different annotations are required)**

Please provide any examples if you have, will be very benefiatial for me.

**Comment by mkmik** [comment]
Most of those points are covered in the documentation, except the part about reaching controllers installed in non standard locations.

The controller by default runs in the `kube-system` namespace and is reachable by a service with a well known name (`sealed-secrets-controller`).
The kubeseal client assumes those names unless told otherwise (via flags or env variables).

The supported installation method is a yaml manifest attached in the release. If you use that file it just works.

I noticed a lot of people (for some reasons) prefer to use Helm to install sealed secrets controller.
The Helm chart is maintained by the community. It works but it's not the official installation method and it has some rough edges. In particular, it causes the controller service name to be prefixed by a random "release name" prefix and also encourages people to install the chart in a namespace of their choosing.
Consequently, you need to tell the kubeseal client about those names by passing the `--controller- same` and `--controller-namespace` flags (there is also an env bar mapping to the flags, please check the release notes documents, it contains stuff not mentioned in the readme).

I'm jumping to conclusions you're using Helm based only on the sheet frequency of this class of questions. Your issue might be different. Let me first know if this unblocks you and you can successfully communicate with the controller (e.g. you can run `kubeseal --fetch-cert`)

**Comment by iamvyom** [comment]
Hi Marko,

Thanks for the reply. I agree my last questions were bad.

I have moved quite ahead and my sealedsecrets are now getting UNSEALED.

A bit of your help will help me setting up the automation flow.
please reply

1. How can i seal a secrets file having more than one secrets in YAML format, **as of now only the 
first secrets is getting sealed.**

2. I have more than 4 environments and thus need to have custom and differernt  certificate/ key pairs to seal/unseal them, can u please provide a solution?

Please reply.

**Comment by mkmik** [comment]
1. Do you mean multiple yaml documents separated by "---"?

**Comment by iamvyom** [comment]
yes

**Comment by mkmik** [comment]
2. You need to seal each secret N times, once for each environment.

I.e. you'll have N sealed secrets files, one for each cluster and when you'll deploy the yaml manifests on a given cluster you'll have to make sure that you pick the right one. Generally, users leverage their favourite k8s manifest templating system in order to help ensure that the right sealed secret values are selected for the given target cluster (e.g. kubecfg, kustomize, helm). Some people maintain multiple copies of whole files, while other people prefer to use templating to conditionally load individual items (and use kubeseal --raw to produce individual encrypted items); I think it boils down to personal preference.

In particular, when updating a single secret that has the same value in all the clusters, you'd also have to update it N timea,. We currently don't have a helper nor a specific example in the documentation that shows how to perform such bulk updates. It should be straight forward to do with a bash oneliner (e.g. with --merge-into).

That said, it's a good practice to avoid having too many shared secrets between clusters and favour having distinct secrets in each cluster anyway.

**Comment by mkmik** [comment]
1. Sadly we don't support that (yet?) And you'd have to manually split the combined yaml file into multiple files

**Comment by mkmik** [comment]
Has the original issue (the one after which this issue is titled) been addressed?
