### ISSUE TITLE
Offline Decrypting a Sealed Secret with kubeseal throws an error

### ISSUE THREAD

**Issue by rafaribe** [bitnami-labs/sealed-secrets#351]
Trying to decrypt a sealed secret with the privatekey file using `kubeseal <mysecret.yaml --recovery-private-key master.key`outputs an error
```
error: converting (v1alpha1.SealedSecret) to (v1.Secret): Data not present in src
```
Steps to reproduce:

1 - Fetch your sealed secret in yaml format: `kubectl get sealedsecrets mysecret -o yaml > mysecret.yaml`
2 -  Extract your privatekey list into a single file: ` kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml >master.key`
3 - Try to unseal the sealedsecret with kubeseal: `kubeseal <mysecret.yaml --recovery-private-key master.key`
4 - Get error: `error: converting (v1alpha1.SealedSecret) to (v1.Secret): Data not present in src`

**Comment by mkmik** [comment]
You also need the `--recovery-unseal` flag to tell kubeseal that's the "command" being preformed (the --recovery-private-key is just a parameter to the --recovery-unseal flag). Yes, this UX sucks.

Thanks for reporting. I'll improve the doc and/or behaviour of `kubeseal` so that users don't fall in this trap.

**Comment by rafaribe** [comment]
Yeah adding to that I was able to successfully decrypt the key using this approach as you told me on the community slack. Thanks for the support !

```kubeseal <mysecret.yaml --recovery-unseal --recovery-private-key master.key```
