### ISSUE TITLE
`encryptedData` in SealedSecret is not deterministic

### ISSUE THREAD

**Issue by ghostsquad** [bitnami-labs/sealed-secrets#376]
I'm trying to understand why whenever I regenerate an SealedSecret, the `encryptedData` changes, even though the value being encrypted has not changed.

EDIT 2020/03/16 20:57 PST

A simple example is the one from the readme:

```bash
echo -n bar | kubectl create secret generic mysecret --dry-run --from-file=foo=/dev/stdin -o json >mysecret.json

kubeseal <mysecret.json >mysealedsecret.json
```

```diff
--- a/mysealedsecret.json
+++ b/mysealedsecret.json
@@ -15,7 +15,7 @@
       }
     },
     "encryptedData": {
-      "foo": "AgB+AygEDUkf1j+uOi8ZzxT140RklBcljElh6gIdlMDcMIidWadSOKaYIOKhAg/fL8JRn6OO6if+uOJjGipdZcMdmdE1COCJX1Y38sRVwwuNo2ObW5fkaKkBCkepbuxHX60EJ0C7cfFdIzQtPg4nqXRxZW+7ArIR+s+ZPwjVkjQPsKbQCo8rZxCoRYLtbitKeeHaVOgAZpvelAffe6ewHEyhZgqjK24B9dbq3DICiR+4iQPmXk4zdcYFLvsgmadIeK/7wpAGzqpdI6rmsiex55IVOkELeaZZwXl+TlxceOEk4Ub07iedXNZQs29iU+yesYgGOQCzNYoPxoLzV98i5MiSRhaiyM8EWU7kZSNx3ZCmch37LRwmBeqlypiNI7BmfWnJQ+KwBe3hyOqi7QComs0YzVXHQ5DXQRwoorUwwNEsoDT5Fy7ZTcMKI4vIaVULG/YOSrHYGFBYq8Q8eB3G5cEvxHne/iUEqWZEWfJxO+O4Fs2h6DzoqMT13o7sBhzHcY2TIHedlsLI7HpJNwcVioDGWFcG/XU80wRHRj+NqnxEzqa8e0+VHaVWBBQa7ggur92vVOd9wCzCiMfBsKSocoOAx/aa26exMmE+4yS1ZQ5Djlt3WM7whZ6MTXq5tOp4GfJy57xpzIwh6YkpELm0VQOnYnArIdqLDxnNb3+Mm/2cWEBXy7+yGCiSWqHhZyMLap1SMU8="
+      "foo": "AgAuOYUW77sFylgELezKAdmlMznGtUJTBtvFOq0k5zesa46Y1PA1BDLlpZbL6KeNi83Cg+O+j0kBZxO5Ca3PH6kv/qMD12y5qg+Z2AftlFHPEapotgWODD+cRxspZNiDtuAAmruUxmT7dCzbEQ2tm+2aelKh3JntoaFAdwVbEuHxgM2VMKpIArrzEoqijg+RPXo9JcLm8RiZW5QcL3ZPWNZoXS/WGkd91MSJcnCktRCVSmIedgX8tsfLPT6Ad2uugTGuPHiRyVzGRgi4Xmsq1h1UFVzpWOblviGyHHkkIsTlC7y3uJi5Q0NQcjHCN+wdfKKsh35lNwsPtkhugbH4NvFi0ZUJt41rZbNgUPy7brCJOUxLPag8uiPkeEZPt6nsIQbKUJqdT9/zaJ0ad4G6x/lvnAKhWNcBDQjFoFk78WPJBT8DyaZwYQV1wg6Wo7LpotPFR1MIjxpaqv6Z+RNWPc2N53rneK0xm0hD1laMZ//tdB9yA5FxDYm33Ms9ZpzkKH0su8wWudYxMw3zk7DRD+Uw7CqtAAtdtK2QsNIA8aZDEhAyfFpLoXee2AscqnfOhhJ0nBaw9bAy83hWIAGw+2dFJIk0gYpMu2AkpHg128RfUg2zSzfpbtahDLpQfKYD5dxQt0fl74ZEsk3qnUsuQ7TI1Af9La9MuHX2LmFJrBsCuTUzTw/tZ8RhBTcuy/1n6Eq8BX8="
     }
   },
   "status": {
```

I don't necessarily mind if this changes when the sealing keys are rotated, since that's the very point of that, but if the sealing key has remained the same, then wouldn't the encrypted value also be the same?

I don't want my users to think that the sealed secret has actually changed, or to force them to needlessly commit a new sealed secret every PR (since I would like to do some sort of automation around recreating the sealed secret automatically).

Can someone provide some clarity around this?

**Comment by mkmik** [comment]
This is by design, we effectively use a random once.

This is usually not a problem since you should only update the items in your secrets that actually change. From your problem description it seems your encrypting the whole secret every time you make a PR (which also seems to imply you keep the original secrets in clearext somewhere else).

Have you looked at the `--merge-into` documentation?

**Comment by ghostsquad** [comment]
@mkmik yes, since as the documentation states, SealedSecrets is not a good place to store the raw secrets value, I'm using AWS Secrets Manager as the source, which is plumbed into a SealedSecret and deployed.

I now see the help string for `--merge-into`, but I'm not sure if that solves my problem, as the secret value still changes.

Due to the fact that this is by design, I think that since I generate the `sha256` of the original secret and store that in the sealed secret as an annotation, I can compare those values before resealing to avoid recreating the sealed secret with a different encrypted data.

Thanks for pointing out that this is by design.

**Comment by mkmik** [comment]
> I'm using AWS Secrets Manager as the source, which is plumbed into a SealedSecret and deployed.

Is it a human or automation that calls AWS Secrets Manager and writes a SealedSecret out?

**Comment by wmcnamee-tunein** [comment]
@mkmik it's automation

**Comment by wmcnamee-tunein** [comment]
I think this can be closed at this point.

**Comment by mkmik** [comment]
I'd like to better understand why are you using it the way you're using it; if anything, so that we can improve our docs.

1. why can't your automation just grab the secret from AWS Secrets Manager and push it to your cluster?

2. I'm a bit confused on "the documentation states SealedSecrets is not a good place to store the raw secrets value". What are you referring to?

**Comment by ghostsquad** [comment]
> why can't your automation just grab the secret from AWS Secrets Manager and push it to your cluster?

For now, I'm trying to get developers into a "GitOps" workflow, such that a deployment of code, configuration and secrets is a "single immutable package" that doesn't magically change without a pull request.

Because of that, although we store secret values long term in AWS Secrets Manager, only a PR will cause the _deployed_ secrets to be updated. Given that these are secrets that don't change often and usually require manual effort to rotate. We have other means of obtaining secrets such as short-lived tokens at runtime.

Identifying "what has changed" when there's an incident should be a matter of looking at Git history, and little else.

> I'm a bit confused on "the documentation states SealedSecrets is not a good place to store the raw secrets value". What are you referring to?

in the `README.md`:

> Can I decrypt my secrets offline with a backup key?
>
> While treating sealed-secrets as long term storage system for secrets is not the recommended use case, ...

**Comment by ghostsquad** [comment]
More information on the various tiers of configuration:

Configuration is unified into 1 of 4 possible places at most. These are ordered by complexity of implementation:

1. the app has reasonable defaults, so the configuration value does not need to be explicit.
2. environment specific values that are not secret (stored in a Makefile or .env file and checked in with Git) are plumbed in as Kubernetes environment variables
3. environment specific values that ARE secret (and don't change often), are stored in AWS Secrets Manager/Vault, with paths/ids that follow a known, predictable pattern, such that automation can lookup and use secrets automatically based on deployment environment or other variables. This does not necessarily need to be limited to the application runtime, but it could also be for secrets used during the Docker build or Terraform apply. For Kubernetes deployments, these secrets are downloaded from AWS SM/Vault and stored in the repo as a SealedSecret using a sha256 suffix for immutability and subsequently are mounted to the pod as environment variables.
4. dynamic configuration such as feature flags & short-lived secrets - TBD

**Comment by mkmik** [comment]
yeah, indeed sealed-secrets is *designed* as a one-way secret store: a human puts a secrets in and the k8s cluster can consume the secret. 

If you need to read the secrets later you either:

1. read them from the k8s cluster itself (admins that have RBAC roles)
2. store the encryption key somewhere safe and decrypt them offline (not recommended outside of disaster recovery).

The main use case are the class of secrets that you don't really ever need to look at twice. "Throw-away" secrets that are easy to regenerate and for which it's a good idea to regenerate them anyway. Think of a database password; think of why would you need to see that password again: a) you're an admin and need to troubleshoot b) you need to reuse this password in some other workload.

In the former case, such admins should either have access to the cluster and thus be able to access the unencrypted secret, or be external users for whom it would be a good idea to create a dedicated account on the DB anyway (for nonrepudiation). In the latter case, just create another account.

Being designed this way doesn't mean you can't use it otherwise, it just means the whole workflow is designed to naturally match this use case.

You have a different workflow: you're storing the secret somewhere else and you want to use sealed-secrets as a way to "snapshot" your secrets into an encrypted form that is decoupled from your authoritative secrets storage mechanism.

Unfortunately your workflow collides with encryption best practices that mandate that encrypting the same message multiple times shouldn't be encrypted to same cyphertext. There are many reasons for that, including the fact that an attacker has no way to know whether two given versions of the secret have the same value or not. The current implementation leaks the less possible amount of information to an attacker; relaxing this would weaken the general case and so I'd be hesitant of doing it.

That said, there might be other solutions to your use case and I'm open to improving the sealed-secrets tool and ecosystem to accommodate that workflow, if possible.

-----

What about this proposal:

Kubeseal gets a new  `--merge-if-modified-hmac key` flag. For cleartext secret intem in the input secret, kubeseal would compute `HMAC(item, key)` and compare it to the value stored in the `sealedsecrets.bitnami.com/item-hmacs` for that item. If the HMAC matches, kubeseal doesn't merge the item, otherwise it merges it and updates the `sealedsecrets.bitnami.com/item-hmacs` annotation.

The key passed to the HMAC should be used by your automation but otherwise kept secret.

The rationale is the same as for random nonce/session key: if an attacker speculates the secret is `bar`, having a sha256 in the secret (or a deterministic encryption) would confirm this speculation.

Example (where the whole sealed secret is not updated because `HMAC(bar, hmac_key) = 6d848505114d8cc5b7ed8306f7a3db96a996ef304b822bd999b37fb76e186771` and thus your automation knows it hasn't changed.

```bash
$ your-code-that-builds-a-secret-from-aws-secret-manager-script >secret-from-sm.yaml
$ cat secret-from-sm.yaml
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  creationTimestamp: null
  name: foo
  namespace: bar
  annotations:
    sealedsecrets.bitnami.com/item-hmacs: "{\"foo\": \"6d848505114d8cc5b7ed8306f7a3db96a996ef304b822bd999b37fb76e186771\"}"
$ cat sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foo
  namespace: bar
  annotations:
    sealedsecrets.bitnami.com/item-hmacs: "{\"foo\": \"6d848505114d8cc5b7ed8306f7a3db96a996ef304b822bd999b37fb76e186771\"}"
spec:
  encryptedData:
    foo: AgBzD20udygh/3f9wvjKitd6naipsBiOAcx....
$ sha256sum sealed-secret.yaml
b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c sealed-secret.yaml
$ kubeseal  --merge-into -oyaml --merge-if-modified-hmac hmac_key sealed-secret.yaml <secret-from-sm.yaml
$ sha256sum sealed-secret.yaml
b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c sealed-secret.yaml
```

**Comment by ghostsquad** [comment]
> The current implementation leaks the less possible amount of information to an attacker; relaxing this would weaken the general case and so I'd be hesitant of doing it.

I'm definitely not opposed to security best practices. My use case is simply "developer surprise", when the sealed secret changes, even though the value has not.

Additionally, I'm not actually storing the full sha of the secrets value, just the first 12 characters, which may or may not hinder an attacker looking to verify suspicion of the value, I'm not sure.

The hmac idea seems very good, and could easily be implemented, since I would simply just store the hmac key in a separate AWS Secrets Manager secret and use it within the automation.

**Comment by gabegorelick** [comment]
I was originally going to ask if allowing `kubeseal` to specify the AES-GCM nonce would better solve this issue. But looking at [the code](https://github.com/bitnami-labs/sealed-secrets/blob/d15c388248912213c930d1dc5b0f84c627bca3ea/pkg/crypto/crypto.go#L35-L71), I see that it's more complicated. A static GCM nonce is already used coupled with a one-time, random AES key. It's this AES key, as well as the `random` parameter passed to `EncryptOAEP`, that would have to be made non-random in order for the SealedSecret to be deterministic. 

My use case is similar to @ghostsquad's. I have a build pipeline that pulls down secrets from the source of truth, calls `kubeseal` on them, and then sends off the resulting manifests to be applied to the cluster. But non-deterministic output from `kubeseal` means we have to be a little smarter about this, e.g. by checking the mtime on our secrets and only resealing them if they've been modified. Otherwise, we'll see a lot of changes to SealedSecrets that make audits and reviews really hard (it's impossible to tell if a Secret actually changed, or if it was just re-encrypted verbatim).

**Comment by adr-arkproject** [comment]
Facing this exact issue - it is confusing our dev team to see a diff for every sealed secret, when only the underlying value for one of them has actually changed. 

@mkmik is there any reason not to implement your suggestion above for `--merge-if-modified-hmac key` flag?

**Comment by mkmik** [comment]
Yeah I really like the idea of only changing the value that changed.

I'd love if somebody reviews the details of my proposal though before implementing it

**Comment by adr-arkproject** [comment]
> Yeah I really like the idea of only changing the value that changed.
> 
> I'd love if somebody reviews the details of my proposal though before implementing it

Cool - I can try to tackle this if you think it's worthwhile ;-)
