### ISSUE TITLE
Issues using kubeseal --recovery-unseal --recovery-private-key

### ISSUE THREAD

**Issue by gemmadlou** [bitnami-labs/sealed-secrets#488]
I've been a beneficiary of this repo and it works great. 

I hadn't attempted to use `kubeseal --recovery-unseal --recovery-private-key file1.key,file2.key,...` before, but in trying to do so, I found it was hanging and I wasn't sure why.

I used it in the following way and it didn't work.
- I used the master key
- I pointed it to a local yaml file

```bash
kubeseal --recovery-unseal --recovery-private-key master.key <file>.yaml
```

Thanks for helping in advanced.

**Comment by mkmik** [comment]
Since v0.9.3, kubeseal show a warning when you forget to pass the input data via standard input (stdin)

```console
$ kubeseal --recovery-unseal --recovery-private-key master.key file.yaml
(tty detected: expecting json/yaml k8s resource in stdin)
```

The correct way is:

```console
$ kubeseal --recovery-unseal --recovery-private-key master.key <file.yaml
```

notice the `<` before the name of the file name. (If you aren't familiar with unix IO redirection, read https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-i-o-redirection)

Also please make sure you upgrade your `kubeseal` binary if you didn't see this warning.
(Let me know if you didn't see the warning despite running a newer version of the client binary)
