### ISSUE TITLE
Secrets weren't recreated after etcd re-init

### ISSUE THREAD

**Issue by Philippians413** [bitnami-labs/sealed-secrets#629]
After network downtime etcd cluster restarted.
After that sealed secrets made force unseal for secrets and updated secrets in source namespace, but not all secrets were recreated.

Logs from sealed-secrets-controller
```
2021/08/25 23:48:31 Updating development/mongodb-client-cert
2021/08/25 23:48:32 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"development", Name:"mongodb-client-cert", UID:"5a581ec0-2188-4845-ab90-419327510077", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"562507248", FieldPath:""}): type: 'Normal' reason: 'Unsealed' SealedSecret unsealed successfully
```

Logs from application (can't find unsealed secret)
```
development 2021-08-25T23:50:28Z Warning FailedMount Pod pod-name-89fcc98c8-wccfr MountVolume.SetUp failed for volume "cert" : secret "mongodb-client-cert" not found"
```

**Comment by yannickbsaq** [comment]
Our issue seems similar to @Philippians413 's issue.

Recently upgraded to SealedSecrets v0.16.0 from v0.15.0 using Helm.

A couple of days later we upgraded our OpenShift cluster and some Secrets "went missing" resulting in some pod creation errors.

The SS controller's logs don't show any attempt to unseal those "missing secrets", nor seem to have received any events that should've triggered SS to unseal those secrets.

Could this be caused by recent changes in #567 and the controller not seeing any changes to the SS resources, thus not creating the secret?

We rollbacked our problematic helm release to the same current revision which triggered the SS to be recreated thus triggering SS's controller to unseal the secret correctly.

Also note that we aren't using the `--update-status` nor the `SEALED_SECRETS_UPDATE_STATUS=1` env var mentioned in the v0.15.0 release notes.
