### ISSUE TITLE
Encrypt each secret separately

### ISSUE THREAD

**Issue by c-knowles** [bitnami-labs/sealed-secrets#63]
Just found this great project today! It looks pretty much exactly what we were considering save for a few details. Would like to contribute some extras, just had a few questions first.

We were likely going to utilize [sops](https://github.com/mozilla/sops) for the main portion of it with a controller or initializer wrapped around it. In terms of differences, there's a few things I'd be interested to gain. Mostly encrypting each secret separately to make diffs meaningful and conflicts easier to resolve. KMS support and CLI editing for those with access to the key might be good too although likely separate issues.

**Comment by anguslees** [comment]
Thanks :)
Yes, the plan is to change to encrypting each key/value separately, similar to sops.  I thought there was a github issue about that, but apparently I'm mis-remembering our internal discussion where we came to this same conclusion.  This shall now become the feature request I was imagining :P 

KMS support is a separate issue, and (at least as I understand KMS) not necessary for sealed-secrets.  Sealed-secrets uses a public/private key pair, and the public key is safe to share widely (provided you can verify that you have the _correct_ public key).  So the idea (with separately-encrypted values) is that _any_ human (limited by your existing RBAC/git-approval/etc write access) can replace any of the values with a _new_ freshly-encrypted secret value, but nobody will be able to retrieve the old value(s) outside the cluster.  This means an "edit" with sealed-secrets is really "replace+seal" rather than "unseal+modify+seal".
A cli to make re-encrypting individual values easy would indeed be a valuable follow-on once we have per-value encryption.

**Comment by c-knowles** [comment]
@anguslees great! Let me know if we can help out. I've filed a separate item for KMS to avoid cluttering this ticket (sorry, should have done that to start with).

**Comment by c-knowles** [comment]
Going to start on this shortly.

**Comment by rasheedamir** [comment]
@c-knowles did you make any progress with it?

**Comment by c-knowles** [comment]
@rasheedamir yes, actually I'm working with @sullerandras who submitted https://github.com/bitnami-labs/sealed-secrets/pull/73.
