### ISSUE TITLE
Periodically resync all secrets

### ISSUE THREAD

**Issue by bakins** [bitnami-labs/sealed-secrets#66]
Currently, the informer does not do a periodic resync: https://github.com/bitnami/sealed-secrets/blob/b86679e5d7cdb3c38dd730f16c20ea5a32dea225/cmd/controller/controller.go#L71

Any objection to a PR to enable this as an option?  We had a used case where this would have been helpful. It looks like it eventually will resync (10 minutes) but we may want to set this explicitly.

**Comment by anguslees** [comment]
Correct, it will resync in various situations (controller restart, watch connection timeout) but doesn't do a resync "just because".

Could you talk more about the situation where this would have been helpful?  In particular, I suspect what you might actually want is to retry errors forever (currently gives up after 5 attempts) rather than periodically repeating successful operations.

**Comment by paprickar** [comment]
Hey @anguslees,

year 2017 is here :smile: 
I just stumbled over this issue and I had a situation where I had existing secret stopping sealed secrets to manage them.

As soon as I saw this issue i removed the secrets but sealed secrets did not created them afterwards as the controller tried already more then 5 times.

I might miss something but a forever retry with increasing interval or a configurable interval would be great.

**Comment by mkmik** [comment]
Hi. Would #224 address your issue?

**Comment by paprickar** [comment]
Hi,

yes Indeed I think that would be good - voted for the issue.

**Comment by kuzm1ch** [comment]
+1
Continuous reconciliation loop is common for controllers/operators nowadays. Due to this users expect from controllers/operators to work like this. 

It will be useful for me f.e. in case of migrating Kubernetes secret to sealed secret (when I was doing it in 2 iterations): 
1. Deploy sealedsecret object -->controller will fail, because an existing secret exists (which is OK)
2. Delete existing secret --> new secret will not be created as sealed(Error updating kube-system/vsphere-config-secret, giving up: failed update: Resource ).

**Comment by juan131** [comment]
Closing issue in favor of https://github.com/bitnami-labs/sealed-secrets/issues/224
