### ISSUE TITLE
Encrypt secret by hand

### ISSUE THREAD

**Issue by k0pper** [bitnami-labs/sealed-secrets#714]
Hello maintainers and commiters,

Love SealedSecrets, helps safely store sensible information in my repos :)

I am writing an application that automatically creates a sealed-secret.json.
- enter some values to encrypt
- converts it into a base64 string
- encrypts it with the Algorithm used in SealedSecrets
- And creates a sealed-secret.json ready to deploy into the cluster

I read that for encryption, these steps are done by kubeseal:
https://github.com/bitnami-labs/sealed-secrets/blob/e89b210dd745eff29f59e1796a42a852c63de7c9/docs/developer/crypto.md
1. Generate random 32 byte session-key
2. Encrypt the secret with AES-GCM (AES-256) (symmetric) with the session key
3. Encrypt Session Key with RSA-OAEP-SHA256 with the controller's pub key
    i. OAEP input parameters (labels): namespace and name of secret 
4. Result is: 
- Encrypted Session Key Length
- Encrypted Session Key
- Encrypted Secret

I have some trouble encrypting the data by hand. The questions that I have are: 
* Why is the session key encrypted with RSA-OAEP-SHA256, if the session key is "single use"?
* Do I only need the pub.cert fetched by `kubeseal --fetch-cert` to encrypt the data? Or do I really need to generate some 32byte session key. Do I have to store that session key or can I throw it away after encrypting?

I am not a cyber security expert, maybe the problem is trivial. Can you explain the steps that are required to encrypt the value "thisIsTopSecret" that is then stored in the "encryptedData" field in the sealed-secret.json? 

Alex

**Comment by mkmik** [comment]
The encrypted payload format will change in the future and if you call the kubeseal tool or the kubeseal Go package you'll benefit from forward compatibility.

Is there a reason why you need to encrypt the secret by hand?

What kind of tool you need to write?

Is this a documentation problem? (I.e. are you aware or the "--raw" command and of the Go package). Or is this because you want to use a specific programming language for which there is no kubeseal library binding?
