### ISSUE TITLE
argocd app shows 'degraded' though the key unsealed sucessfully and sealed secret health status shows wrong

### ISSUE THREAD

**Issue by sandeepitachi** [bitnami-labs/sealed-secrets#739]
Controller version - v0.17.1

I just deployed argocd and declared the argocd creds using sealed secrets - secrets got unsealed successfully and everything's working fine BUT the argocd app health shows as DEGRADED as it failed first few times App health status still shows the previous error while the live state is good

https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories

**Expected behavior**
App status should be healthy and sealed secret health status should show the correct message 'unsealed sealed secret successfully'

**Version of Kubernetes**:

v1.21
**Actual behavior:**

Output:
![image](https://user-images.githubusercontent.com/25717719/153220798-21027021-f005-4eb2-86ad-5f52e57e9e9d.png)
![image](https://user-images.githubusercontent.com/25717719/153220843-d903635e-ecfc-49ed-a0ca-79e1c14f4527.png)

sealed secrets got decrypted and argocd is working fine. Only problem is the app status shows degraded and sealed secrets health status shows wrong

**Comment by Yeicor** [comment]
This issue is still relevant: if the secret fails to decrypt at least once (i.e. the master key is not uploaded yet), the `status.conditions` is not updated when the secret is correctly decrypted.

This can cause the whole Argo CD deployment to get stuck because the sealed secrets are not detected as healthy.

![Screenshot_20230214_205139](https://user-images.githubusercontent.com/4929005/218849346-1d721852-92fd-456a-835a-ff23e21207c2.png)
![Screenshot_20230214_211348](https://user-images.githubusercontent.com/4929005/218851385-c5aa7223-cc0d-4e02-ab11-0f886d394432.png)

Searching through at the code, it looks like this condition is **the reason the status is not updated:**

https://github.com/bitnami-labs/sealed-secrets/blob/58b88645127bc3c67b0ddb55fd37cc12bd39f05e/pkg/controller/controller.go#L356-L360

Is this condition required for some reason or can it be removed to fix this issue? I guess it is also possible to bump the generation when a secret is successfully decrypted.

**Comment by stand-sure** [comment]
commenting as the issue still exists

a major concern with an app being stuck in degraded even though it succeeded is that it conditions users to stop checking why the app shows as degraded, which could cause a real issue to be missed

**Comment by zatricky** [comment]
@agarcia-oss can this issue be re-opened?

**Comment by DreamingRaven** [comment]
can confirm I am also having the very same issue. My secrets are decrypting, but argocd is still reporting a degraded sealed secret.

**Comment by lhbarry** [comment]
Same issue here, and very interested in a resolution

**Comment by jgracindexcom** [comment]
Same issue.

**Comment by bernardab0806** [comment]
Also having the same issue.
