### ISSUE TITLE
Documentation needs to list cipher and bitlength

### ISSUE THREAD

**Issue by iMartyn** [bitnami-labs/sealed-secrets#80]
This looks like an awesome project but there's no technical detail about the strength of the cipher or what cipher is being used.

I'd love to add this to the list of options when presenting but there's no detail and I don't want to dig through the code to find the answer to this kinda important question!

**Comment by arapulido** [comment]
Thanks for your suggestion. I agree this should be in the project documentation. In the meantime, you can check what cipher it's being used in this blog post: https://engineering.bitnami.com/articles/sealed-secrets.html Let me know if that helps.

**Comment by anguslees** [comment]
Thanks, fixed in the above README.md commit.  Documentation is not my strong point, let me know if there's anything more you'd like to see ;)
Note the RSA key size is configurable via a controller command line flag - and should be printed to the controller log during key generation.

Note also there's no algorithm / key-length negotiation in the serialised form, since we basically get forward-compatibility for free from the CRD apiVersion (this may change in future, but again we can manage that transition by incrementing the apiVersion).

Again, let me know if you've got any outstanding questions.
