### ISSUE TITLE
Kubeseal --re-encrypt can be done without kube-system namespace access or cluster access

### ISSUE THREAD

**Issue by gabrielhao** [bitnami-labs/sealed-secrets#842]
**Which component**:
kubeseal --re-encrypt

**Is your feature request related to a problem? Please describe.**
We use pipeline to encrypt and re-encrypt secrets and sealed-secrets yaml files. For encryption we can do it without cluster access. However for dealing with key rotation we need to use `--re-encrypt`, it requires access to "kube-system" namespace. It is so far not possible. 

**Describe the solution you'd like**
`--re-encrypt` can be used as encryption without cluster access just with cert files.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by mkmik** [comment]
the current "re-encript" functionality *is* the feature that allows you to re-encrypt the sealed secret without knowing the primary key, and thus by definition it requires access cluster access.

If you want an "offline" re-encrypt functionality all you need to do is to decrypt with `--recovery-unseal` and pipe the resulting cleartext back into `kubeseal` (likely with offline encryption, i.e. with `--cert` flag) in order to get a newly encrypted secret.

```console
$ kubeseal --recovery-unseal --recovery-private-key private1.key <old.yaml | kubeseal --cert public2.pem -w new.yaml
```

Read more about the offline decryption in https://github.com/bitnami-labs/sealed-secrets#can-i-decrypt-my-secrets-offline-with-a-backup-key
