### ISSUE TITLE
idempotent command

### ISSUE THREAD

**Issue by jalberto** [bitnami-labs/sealed-secrets#93]
i am trying to use Sealed-Secrets as part of my CI/CD flow, but it requires extra logic to run different commands depending on if the secret is already installed or not.
Ideally same command should take care of it.

**Comment by c-knowles** [comment]
We're using `kubectl apply -f sealedsecret.yaml`, seems to work fine for create and update.

**Comment by anguslees** [comment]
@jalberto could you give an example of the issue you're having?  I'm not clear why you would need to know if the secret already existed or not.

**Comment by jalberto** [comment]
@anguslees when I deploy an existing helm chart that already creates it's own secret seems more natural to me to use `replace` instead of apply.
But I can see doing `apply` seems to work as expected, just confusing if you are use to vanilla kubectl

**Comment by anguslees** [comment]
@jalberto I'm still trying to work out the scenario you're describing.   I _think_ what you're talking about is this sequence:

1. `helm install somechart_that_creates_a_secret`
2. Create a SealedSecret version of that Secret.
    Something similar to: `kubectl get secret chartsecret -o yaml | kubeseal > sealedsecret.yaml`
3. `kubectl replace -f sealedsecret.yaml`

Is that last command what you're talking about?

**Comment by jalberto** [comment]
@anguslees exactly that :)

**Comment by anguslees** [comment]
@jalberto ah right.  I know it's not a helpful answer, but how `kubectl` works is not something `sealed-secrets` can change :(  As @c-knowles responded, the `kubectl` subcommand for update-or-create is `apply`.

I guess the surprise from adding sealed-secrets to the mix is that you're now manipulating a different SealedSecrets resource, not the usual/existing Secret - so the SealedSecrets resource is highly likely to not exist the first time you run one of these commands.  @jalberto I'm going to close this issue because I don't think there's anything for us to do here - but if there's some sealed-secrets docs or example you found unclear, please point it out and we can work on improving that.
