### ISSUE TITLE
Raw mode does not work on windows: open /dev/stdin: The system cannot find the path specified.

### ISSUE THREAD

**Issue by matbarker** [bitnami-labs/sealed-secrets#934]
**Which component**:
Kubeseal v0.18.2

**Describe the bug**

Expected to be able to use --raw option using the example command from the readme but got the error:
`error: open /dev/stdin: The system cannot find the path specified.`

**To Reproduce**

In a Powershell or Command window:
Run `echo -n "mypassword" | kubeseal --raw --from-file=/dev/stdin --namespace default --name my-test-secret --controller-name=sealed-secrets       --controller-namespace=kube-system`

outputs: `error: open /dev/stdin: The system cannot find the path specified.`

The command succeeds in a windows bash shell, but the encrypted password ends up being (base 64 decoded): 
`!<symlink>/�p�r�o�c�/�s�e�l�f�/�f�d�/�0���` instead of `mypassword`

**Expected behavior**
Expected output of an encoded version of 'mypassword' string.

**Version of Kubernetes**:
Docker desktop kubernetes v1.24.2

- Output of `kubectl version`:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by josvazg** [comment]
When running a command such as:
```shell
$ echo -n "mypassword" | kubeseal --raw --from-file=/dev/stdin --name my-test-secret ...
```

The tool is encrypting the string "mypassword" using the key from the cluster. The result from standard output is a _base64_ encoded **encrypted value**. This result is different each time you run the command and should not match "mypassword", but instead the Kubernetes cluster should be able to use its key to decrypt encrypted string back into "mypassword".

Note the documentation about the `raw` option says:
> In the meantime, we offer an alternative mode where kubeseal only cares about encrypting a value to stdout, and it's your responsibility to put it inside a SealedSecret resource (not unlike any of the other k8s resources).

As you can see, using raw implies several steps apart from encrypting the secret before the cluster can read the original string.

Can you share the exact sequence of commands you tested?

**Comment by mkmik** [comment]
it also doesn't help that on windows there is no /dev/stdin

**Comment by deepy** [comment]
I've had a similar issue on Windows, although I don't think I passed `--from-file=/dev/stdin` but the base64 decoded value of the secret had an invisible character show up between every letter.
So instead of the `pass` that was sealed into a secret the Kubernetes secret contained `p�a�s�s�`.

I'll see if I can reproduce it tonight.

**Comment by josvazg** [comment]
We have now removed the `--from-file=/dev/stdin` from the documentation so that the instructions should now work for all supported platforms, including Windows.

Note that `--from-file=/dev/stdin` was not required, as the tool defaults to use standard input unless `--from-file` is set otherwise.

We are closing this issue now, but do not hesitate if you still have problems following the readme in Windows. If so, that could be a separate problem.
