### ISSUE TITLE
Command to add/update an existing sealed secret

### ISSUE THREAD

**Issue by cknowles** [bitnami-labs/sealed-secrets#95]
Now we have per-key encryption, perhaps we could add a command which takes an existing sealed secret plus the details of a new individual key/value and adds/updates it as appropriate. This workflow can happen right now but requires a diff and manual merge.

I'd imagine it could work a bit like `from-literal` part of the kubectl create secret:
`kubectl create secret generic prod-db-secret --from-literal=username=produser`

**Comment by mellena1** [comment]
I definitely see value in this. I like the idea of mimicking how [ansible-vault's](https://docs.ansible.com/ansible/latest/cli/ansible-vault.html#edit) edit command works. I think there are some parallels in what kubeseal and ansible-vault are doing at the end of the day, and ansible-vault's command feels very fluid and intuitive.

**Comment by kskewes** [comment]
Interesting, what are the use cases everyone did +1 for?

I was just wondering if could pipe a string/value to `kubeseal` to encrypt so I could update a sealed-secret without original k8s secret (and unencrypted values).
eg: 
```
kubeseal --cert public.cert --encrypt-string
<paste string>
<ctrl+d>
encryptedString: <encrypted value>
```
Then this value could be copy-pasted into the sealed-secret.json.
Potentially require/assert the string is base64 encoded?

Some sort of flag `--{add|update}key <key>` to do this would be tidier. 
Whilst I would probably just use a text editor, a `--deletekey <key>` flag would complete the functionality.

That said, if storing the full k8s secret object in a password manager then maybe this wouldn't be that useful and might lead to abuse and misplaced secrets?

@mellena1, I think `edit` might be tricky because it would require access to the private key to decrypt the sealed-secret for viewing/editing. I personally prefer to optimize the current 'overwrite only' flow.

**Comment by yann-soubeyrand** [comment]
Having the ability to create an encrypted value directly from a litteral (not base64 encoded) would be great: this way one can easily generate an encrypted value to put in an Helm chart's values.yaml file which a SealedSecret template takes its values from.

**Comment by anguslees** [comment]
I figure there are two "styles" of kubeseal usage that we want to move towards:

#### single value

This is what we don't currently have, and I think should become the "normal" way to use kubeseal.  I'm imagining something like:
```sh
echo mysekret | kubeseal --namespace foo --secret-name bar -f -
```
.. and that just dumps out a base64 (encrypted) blob that you can add as the value for something in the foo.bar SealedSecret.

This (or variations on this, like taking value from command line, or from a file) is the basic primitive for using "per-key" encryption.

#### whole (sealed) secret operations, except using per-key values

This would be things like:
 ```sh
echo mysekret | kubeseal -n foo --secret-name bar -f - --set-value password -o yaml
```
... and that would read the current `foo.bar` SealedSecret, add the encrypted version of `mysekret` to `data.password` within the SealedSecret, and then dump the updated object to stdout.  This is just a helper for what you could do yourself using the earlier command.

Maybe a `--full-secret` option (don't like this name) to expect an entire Secret on stdin, and it will encrypt each key.  This allows similar usage to the current piplines like:
```sh
kubectl create -f docker-registry.yaml --dry-run |
   kubeseal --full-secret -f - |
   kubectl apply -f -
```

(Note to self: Remember we need easy options for docker-registry and tls secret types too! (I overlooked non-generic secrets in the last big reshuffle, oops))

---

Thoughts? Suggestions?
It would be very useful to have a plan here before embarking on the change, just so we have some consistency across command line flags, etc.  In particular, I don't want to reimplement `kubectl`.  Eg: I would much rather suggest people pipe to `kubectl apply -f` than duplicate the code for doing object updates.

**Comment by ceralena** [comment]
Hi folks,

@yob and I have done some work on a branch in our fork with the dual purpose of a) figuring out the ideal `sealed-secrets` workflow for our own organisation, and b) pushing this discussion forward. There were a number of good ideas above and we'd like to help flesh them out. Below is the [commit message](https://github.com/greensync/sealed-secrets/commit/335d5317a4adb4a41e793eb839946f088966889b); hopefully this is food for thought.

---

This work was done as a quick experiment in building a viable
alternative CLI to `sealed-secrets` inspired by the discussion in
bitnami-labs#95

We're hoping that this helps to drive the discussion around improvements to the
command-line UX, with a focus on keeping it simple and explicit.

This is a somewhat opinionated design, where different functions are broken up
into sub-commands. In my view, a flag should modify or specify
parameters for a behaviour or action that has been set explicitly, not
trigger that action itself.

Here's the help file:

```
$ ./gskubeseal --help
NAME:
   gskubeseal - CLI tool to create and managed sealed-secrets

USAGE:
   gskubeseal [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
     fetch-cert  fetch and cache the cert / public key from the sealed-secrets controller in ./sealed-secrets.crt
     create      create a new SealedSecret object with a single encrypted key and value and output to stdout
     append      append a new key and encrypted value to an existing SealedSecret provided on stdin and output the updated object to stdout
     help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

In this tool, `create` sets up the `Secret` data structure on your behalf, and
uses that to construct the `SealedSecret` - so there's no need to run something
like `kubectl create secret --dry-run`, as in the previous docs, to bootstrap a
new SealedSecret.

The existing `kubeseal` usage does support a nice use case where you can pipe
your *existing* secrets into the tool while migrating to sealed-secrets; I
think this could be supported by a separate subcommand called something like
`create-from-secret`.

Another opinionated change is for `fetch-cert` to always save the cert to a
local file, with the other commands assuming that file is there. I think that
support for offline use is one of the best features of `sealed-secrets`, and
encouraging this as the default behaviour simplifies a number of things for users:

* no need to ensure that you have network access to the cluster
* no need to remember to include `--cert`
* no need to remember to specify `--controller-namespace` and/or `--controller-name` when you don't have a cached local cert (except when running `fetch-cert`)

---

We made two changes to the code in `pkg` to support this work:

* the `SealedSecret` type now has an `Append` meethod
* `labelFor` needed a refactor to separate out the logic to just build the
label, so that it could be reused in `Append`

---

I hope this effort is not taken as a critique of the existing tool. The
`kubeseal` that exists today is functional and simple - it just doesn't
quite implement the workflow we'd like to provide to our developers.
This was just a few hours' work, and is intended to give a concrete
example of the kind of design we'd like to see. I think the fact that we
could smash out a tool like this in a few hours speaks to the soundness
of the overall architecture. It would even be possible to maintain this
as an alternative CLI in our own repository, with the
`sealed-secrets` repository vendored.

**Comment by Crevil** [comment]
@ceralena That command layout is by far more as I would expect it and it simplifies the usage considerably. 🎉

**Comment by anguslees** [comment]
> I hope this effort is not taken as a critique of the existing tool.

Hell no!  The existing kubeseal was based on the older approach of whole-secret encryption and it really doesn't make sense in the newer individual-value style encryption.  I really like that you've followed through and tested something concrete in both implementation and usage, and then contributed that experience to everyone else.

My only minor tweak to the above would be changing `append` to something that just encrypted a single value for a particular SealedSecret namespace/name - and then left it up to a human to cut+paste that into the right place.  I think that's the most-primitive operation that kubeseal needs, and the rest is all fancy combinations on top of that operation.  Actually, we probably want this single-value operation _and_ convenience things like `set <key> <value>` that does append-or-modify.

**Comment by ceralena** [comment]
Thanks for the feedback. We were 50/50 between the `append` usage and what you suggest there - there are arguments either way. I think your suggested usage provides the most flexibility and is the most simple, so I've updated the tool on our branch to work that way:

```
$ gskubeseal --help
NAME:
   gskubeseal - CLI tool to create and managed sealed-secrets

USAGE:
   gskubeseal [global options] command [command options] [arguments...]

VERSION:
   335d5317a4adb4a41e793eb839946f088966889b+dirty

COMMANDS:
     fetch-cert  fetch and cache the cert / public key from the sealed-secrets controller in ./sealed-secrets.crt
     create      create a new SealedSecret object with a single encrypted key and value and output to stdout
     encrypt     encrypt a single value to add as a new key to an existing SealedSecret provided on stdin and output the encrypted key-value pair on stdout
     help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

```
$ gskubeseal encrypt --help
NAME:
   gskubeseal encrypt - encrypt a single value to add as a new key to an existing SealedSecret provided on stdin and output the encrypted key-value pair on stdout

USAGE:
   gskubeseal encrypt [command options] [arguments...]

OPTIONS:
   --name value, -n value         name of the Kubernetes secret
   --namespace value, --ns value  Kubernetes namespace for the sealed secret
   --value value, -v value        plain text value to encrypt in the sealed secret under this key
```

```
$ gskubeseal encrypt --name foo --namespace bar --value bang
AgBa-rorMUFLtbwyFlEw05DdSQB-63pG0kmqbZot4EbmWd5eUlZtNb8PTC2XKpgsx9ZsH97WxTGtS7s-x_NUGvoWGoh2KewpvhABIziS09xwVOrebkl6iAboE3lOHLDPi4k4yzjaIeH2MH6HenAR_0DXDKa5a1EOunu-nq2Oxqm6iZ_N6ZE64dueRllHOtlKcRqVynVrFIvKwSfTyHv_p6hkkfGnoq2jmOyf2xLhJBupk9qBffqwTgHwahDOx-tCMFBggC9GktEqpuq0BuxyulQGev4JBBdtBKBjdfi1vz-clsOLxTBStCJn6yswQUIYCzI8W1mIZL2k3UWZIS9i1SrmJuOWYQKUBH_72yfrrjlGUxGEDQxQiL-rQr25CWd7oqgGHsUCzNrD4kYX62SBXCLR3YIggJZIt_xUG8-5qXaw79BtufBVRrA1pbA1lFm10VyUTO34UzzKrSYix4lrYbVr_hvmnO7xgok4U0Ty8_47z8UgIDQv7lglYcltJM5c3JjXc8crCrX5duMiYiqrnhcLoKKt5z4Xw-HAAqjFodURVSLWUa4xkQYqymcTzd_B09379qqcRiljEIPrETIJaNzMcsIk_JN6k50VwhQAOzRr0Iyq4-KOyVSCYKnN-uuXaULdcn3iGVmAbdabI_hnavCOUXNAhTwtBToMlg9Bbd6V_KJkZa0EJAf1jtdYbdZtr4Qz3LUh
```

We're rolling out a workflow using our variant of the tool this week with some of our dev teams, so hopefully we'll iron out any issues with the workflow soon.

**Comment by Crevil** [comment]
I agree regarding `append`. The `encrypt` command will be easier to script around.

**Comment by ceralena** [comment]
We just had a conversation about the new `encrypt` sub-command and realized that one use case that is not well-supported by our proposed new interface is multi-line plaintext values for secrets.

We propose that the `--value` argument to both `create` and `encrypt` is made optional, and that the plaintext value is read from `stdin` in that case. This makes it easy to pipe in a multi-line value, but maintains the simple single-command usage for all other uses of all the tool.

It's trivial to add - but please sing out if anyone thinks that's a questionable UX.

**Comment by Crevil** [comment]
Good catch. I think the `stdin` approach will be what we will use mostly (If a new release is cut with this) as it's convenient for scripting.

**Comment by kaspernissen** [comment]
Great job @ceralena! I'm very interested in seeing this merged.

**Comment by mkmik** [comment]
I like it very much too!

**Comment by ceralena** [comment]
We've been using a private fork of the CLI tool at GreenSync for a couple of months now.

I'd be happy to update our public fork with what we've been doing for review - though I am mindful that this would be a breaking change to the CLI.

**Comment by mkmik** [comment]
@ceralena please, I'd love to take a look! I'll try to preserve backward compat if possible though, so I might just use that as inspiration

**Comment by ceralena** [comment]
@mkmik hey there! Sorry for the delay.

I've updated a branch on our public fork with the code for the forked client-side tool we've been using - we call it `gskubeseal`:

https://github.com/greensync/sealed-secrets/blob/gskubeseal-cli-experiment/cmd/gskubeseal/main.go

They key difference from the iteration discussed above is the addition of the `convert` sub-command, which our developers have found quite useful. It takes in a `Secret` and outputs a `SealedSecret`. Some of our developers have found that when they need to add / update an existing sealed secret, they typically prefer to just pull the plain secret out of the cluster with `kubectl get secret`, modify it in place, run it through `gskubeseal convert`, and commit the updated version. 

```bash
$ gskubeseal help
NAME:
   gskubeseal - CLI tool to create and managed sealed-secrets

USAGE:
   gskubeseal [global options] command [command options] [arguments...]

VERSION:
   unknown

COMMANDS:
     fetch-cert  fetch and cache the cert / public key from the sealed-secrets controller in ./sealed-secrets.crt
     create      create a new SealedSecret object with a single encrypted key and value and output to stdout
     encrypt     encrypt a single value to add as a new key to an existing SealedSecret provided on stdin and output the encrypted key-value pair on stdout
     convert     convert an existing Secret provided in stdin into a SealedSecret on stdout
     help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

Food for thought. Let me know if you have any questions. Here at GreenSync we're committed to supporting the project with development time, so we are more than happy to work with you on improving the CLI regardless of the approach you'd like to take.

**Comment by grossvogel** [comment]
I apologize if this is off topic, but I've been looking at this awesome tool and wondering specifically about updating existing secrets. Can somebody tell me whether the work planned for this feature would allow e.g. adding new data to a sealed secret whose encryption key has been rotated out?

My impression is that (a) each sealed secret currently has a single applicable encryption key and (b) older secrets aren't automatically re-encrypted upon key rotation and (c) only the _latest_ key is currently accessible to the client... but maybe / hopefully I'm missing something?

**Comment by pikeas** [comment]
Are there plans to merge @ceralena's fork?

**Comment by juan131** [comment]
I'll proceed to close this issue.

kubeseal has support for the flag `--merge-into` since version `v0.9.2` providing support for this feature request. You can find information about the feature in the link below:

- https://github.com/bitnami-labs/sealed-secrets#update-existing-secrets

Feel free to reopen it if you still consider this requires further discussion.

**Comment by ryan0x44** [comment]
For folks using Helm & Sealed Secrets, I've built a little wrapper to make it easier/less error prone to rotate secrets over here: https://github.com/ryan0x44/kubesealplus - feedback/issues welcome! Not sure it makes sense to bring any of this into kubeseal itself because not everyone uses Helm but open to discussing :)
